### ISSUE TITLE
New snapping modes: Centroid and middle of a segment (midpoint) (#33622)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4949] opened 2020-03-02 08:02 UTC
Original commit: https://github.com/qgis/QGIS/commit/dfa5cb68aa72e2a0aa43c7afec8f1fddc828e36b by web-flow

Snap on centroid and midpoint segment [FEATURE][needs-docs]

**Comment by DelazJ** [comment] 2020-03-02 14:24
Duplicate of #4950

**Closed by DelazJ** 2020-03-02 14:24 UTC
Labels: 3.12, Automatic new feature
