### ISSUE TITLE
Merge pull request #4134 from nyalldawson/save_task

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1687] opened 2017-02-14 03:39 UTC
Original commit: https://github.com/qgis/QGIS/commit/edb30a2191b1a4e2b63fc71f7df86aeb0603fcdf by web-flow

[FEATURE] Background saving of vector layers

**Comment by DelazJ** [comment] 2017-02-14 08:39
duplicate of #1686

**Closed by DelazJ** 2017-02-14 08:39 UTC
Labels: Automatic new feature
