### ISSUE TITLE
the link to data module 9.4 of training manual does not work

### ISSUE THREAD

**Issue by mikmarconi** [qgis/QGIS-Documentation#2653] opened 2018-05-27 22:39 UTC
## Description

Include sentences with details describing the issue you have encountered (e.g., actual behavior, expected behavior, steps to reproduce).

## Checklist
> This is the issue/bug trackers for [QGIS Documentation](https://docs.qgis.org).
Cleaning the queue is a process done by project maintainers, mostly on a volunteer basis.
We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items.

- [x] I'm aware this repository is about QGIS Documentation and the issue I'm reporting is related to its usage.
If it's related to QGIS application or website, please refer to http://qgis.org/en/site/getinvolved/development/bugreporting.html
for the right issue tracker or to the [support channels](http://qgis.org/en/site/forusers/support.html)
- [ ] I have added a link to the page concerned by the issue

**Comment by DelazJ** [comment] 2018-06-07 08:30
Duplicate of #2456 hence closing...
Sorry for the inconvenience, we are trying to find the source.

**Closed by DelazJ** 2018-06-07 08:30 UTC
