### ISSUE TITLE
[FEATURE] [DBManager] Add a GeoPackage dedicated plugin

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1463] opened 2016-10-24 08:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/3f2866c47a0fc2960bd7c3760f242be8dce2c680 by rouault

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-10-25 08:50
duplicate of #1467

**Closed by DelazJ** 2016-10-25 08:50 UTC
Labels: Automatic new feature
