### ISSUE TITLE
[needs-docs] Fixes intersection on (multi)linestring/polygon Z, M and ZM. Fixes #21422

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3654] opened 2019-04-08 05:47 UTC
Original commit: https://github.com/qgis/QGIS/commit/155e0eb5078cf0f113ac1dc69e7b40a063ff38ac by lbartoletti

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2019-04-12 11:17
Duplicate of #3675 (backport)

**Closed by DelazJ** 2019-04-12 11:17 UTC
Labels: Automatic new feature
