### ISSUE TITLE
Merge pull request #7313 from PeterPetrik/mesh_layer_styling_gui

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2753] opened 2018-06-28 13:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/97addfc2cce1c94cd8565d4b4bbb35a429e3d59f by web-flow

[mesh] [feature] App widgets for styling mesh layers

**Comment by DelazJ** [comment] 2018-06-28 13:18
Duplicate of #2752

**Closed by DelazJ** 2018-06-28 13:18 UTC
Labels: Automatic new feature
