### ISSUE TITLE
Merge pull request #2619 from mhugent/zoom_to_feature

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#753] opened 2016-01-12 15:20 UTC
Original commit: https://github.com/qgis/QGIS/commit/3febba279de74a57fa26bc308e6b1cb12dada58d by mhugent

[FEATURE]: Zoom to feature with right-click in attribute table

**Comment by yjacolin** [comment] 2016-01-12 15:23
duplicate of #752

**Closed by yjacolin** 2016-01-12 15:23 UTC
Labels: Automatic new feature
