### ISSUE TITLE
[feature] ability to remove custom functions (fix #27513)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5370] opened 2020-04-30 06:38 UTC
Original commit: https://github.com/qgis/QGIS/commit/e72f021f81e0b7a87ebacbcaaa22e70149e77a08 by alexbruy

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-04-30 06:50
Duplicate of #5372

**Closed by DelazJ** 2020-04-30 06:50 UTC
Labels: 3.14, Automatic new feature
