### ISSUE TITLE
Merge pull request #4942 from gacarrillor/relation_reference_widget_fixes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2016] opened 2017-07-30 12:15 UTC
Original commit: https://github.com/qgis/QGIS/commit/cf753e9ff4778d62b632b88f203b8e3285b06677 by web-flow

[needs-docs] Relation Reference Widget: Add option to show/hide Open Form Button

**Comment by DelazJ** [comment] 2017-08-06 21:33
Duplicate of #2015

**Closed by DelazJ** 2017-08-06 21:33 UTC
Labels: Automatic new feature
