### ISSUE TITLE
Merge pull request #2575 from slarosa/style_grp_layers

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#718] opened 2015-12-13 10:48 UTC
Original commit: https://github.com/qgis/QGIS/commit/2d9f36100e70f774455910ca851accde96e1d3f9 by nyalldawson

[FEATURE] allow applying the same style to selected layers or to legend group

**Comment by DelazJ** [comment] 2016-05-11 05:35
duplicate of #717

**Closed by DelazJ** 2016-05-11 05:35 UTC
Labels: Automatic new feature
