### ISSUE TITLE
Merge pull request #7809 from nyalldawson/metasearch_local

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2962] opened 2018-09-06 01:19 UTC
Original commit: https://github.com/qgis/QGIS/commit/dd3bbf01ced29672674604a59304be66a88db0d1 by web-flow

[FEATURE][metasearch] Add FILE:GEO to known link types

**Comment by DelazJ** [comment] 2018-09-06 05:55
Duplicate of #2961

**Closed by DelazJ** 2018-09-06 05:55 UTC
Labels: Automatic new feature
