### ISSUE TITLE
[MESH][FEATURE] use only specified dataset group (#36334)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5494] opened 2020-05-14 07:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/838faf8a3f95742ca2a46693e0bdfe3710f48bf5 by web-flow

[MESH][FEATURE] Allow to select only specific subset of dataset groups in mesh layer tree 

This could be done in the mesh layer properties dialog in the source tab.
A new tree view displays all the available dataset groups from the data provider. The dataset groups can be checked/unckecked and renamed.
This widget provides also buttons to load extra dataset group from files, to expand/collpase the tree, to check/unchek all items and to reset to default from the provider (for now, only the original name).
Then only the checked dataset group will be displayed in the active dataset widget in renderer settings.

**Comment by DelazJ** [comment] 2020-05-15 12:00
Duplicate of #5495

**Closed by DelazJ** 2020-05-15 12:00 UTC
Labels: 3.14, Automatic new feature
