### ISSUE TITLE
Merge pull request #4606 from nyalldawson/feature_locator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1933] opened 2017-06-01 08:54 UTC
Original commit: https://github.com/qgis/QGIS/commit/a6358b1fc249b924bb40cdc070299a704e8d4490 by web-flow

[FEATURE] Active layer feature locator filter

**Comment by DelazJ** [comment] 2017-06-01 09:01
duplicate of #1932

**Closed by DelazJ** 2017-06-01 09:01 UTC
Labels: Automatic new feature
