### ISSUE TITLE
Merge pull request #3723 from nirvn/regexp_matches

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1510] opened 2016-11-07 04:34 UTC
Original commit: https://github.com/qgis/QGIS/commit/3c530a62e50adc40f9396cf2f22b7974caf29428 by web-flow

[FEATURE] add regexp_matches() function

**Comment by DelazJ** [comment] 2016-11-07 07:31
duplicate of #1509

**Closed by DelazJ** 2016-11-07 07:31 UTC
Labels: Automatic new feature
