### ISSUE TITLE
[FEATURE] active layer locator filter field name restriction

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6092] opened 2020-09-09 12:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/ccb87207ae0034b7f89e7484d78f30e5e41f4df4 by 3nids

the filter can now restrict the search to a specific field by typing @+field_name

auto-completion is provided for the field names

**Comment by DelazJ** [comment] 2020-09-09 12:03
Duplicate of #6094

**Closed by DelazJ** 2020-09-09 12:03 UTC
Labels: 3.14, Automatic new feature
