### ISSUE TITLE
[FEATURE] Client side default field values

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1363] opened 2016-08-30 03:25 UTC
Original commit: https://github.com/qgis/QGIS/commit/4d5bae22b8af6ca77fc128c6a196b38af7d8b572 by nyalldawson

Allows an expression to be set for a vector layer field which
is used to evaluate a default value for this field.

A new method,
QgsVectorLayer::defaultValue( int index,
                              const QgsFeature& feature = QgsFeature(),
                              QgsExpressionContext* context = nullptr )
has been added which evaluates the default value for a given field
using the optionally passed feature and expression context. This
allows default values to utilise properties of the feature
which exist at the time of calling, such as digitized geometries.
The expression context parameter allows variables to be used
in default value expressions, making it easier to eg insert
a user's name, current datetime, project path, etc

Default values are set using QgsVectorLayer::setDefaultValueExpression()
and retrieved using defaultValueExpression()

**Comment by DelazJ** [comment] 2016-08-30 10:58
duplicate of #1365

**Closed by DelazJ** 2016-08-30 10:58 UTC
Labels: Automatic new feature
