### ISSUE TITLE
[FEATURE] Add project load profile times to debugging tools dock

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5771] opened 2020-06-28 05:50 UTC
Original commit: https://github.com/qgis/QGIS/commit/005ac8af2bf8898af24c9b053e15596124cbce88 by nyalldawson

Now it's possible to get a breakdown of the various stages of
project load, in order to identify the causes of slow project
load times.

TODO: in 99% of cases this will be caused by one or more layers,
so it would be nice to further break down the individual layer load
times, e.g. so that for a WFS layer we see the time taken for
the initial server capabilities queries, etc...
For now, you just get the overall load time of each individual
layer.

**Comment by DelazJ** [comment] 2020-06-28 06:21
Duplicate of #5772

**Closed by DelazJ** 2020-06-28 06:21 UTC
Labels: 3.14, Automatic new feature
