### ISSUE TITLE
Merge pull request #3925 from alexbruy/shortcuts-search

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1610] opened 2017-01-03 08:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/47130a67584246f163b13c24197d129433f2ea4c by web-flow

[FEATURE] add search bar to the Configure Shortcuts dialog (fix #12681)

**Comment by DelazJ** [comment] 2017-01-03 08:42
duplicate of #1609

**Closed by DelazJ** 2017-01-03 08:42 UTC
Labels: Automatic new feature
