### ISSUE TITLE
Merge pull request #4433 from nyalldawson/blur_buffer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1850] opened 2017-04-30 00:14 UTC
Original commit: https://github.com/qgis/QGIS/commit/b587282186b8b778c22e95f73001f2b56031a336 by web-flow

[FEATURE] Allow paint effects for label buffers & backgrounds

**Comment by DelazJ** [comment] 2017-04-30 02:16
duplicate of #1849 and #1848

**Closed by DelazJ** 2017-04-30 02:16 UTC
Labels: Automatic new feature
