### ISSUE TITLE
Merge pull request #31533 from 3nids/classification_logarithmic

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4193] opened 2019-09-03 13:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/2001e0fcf510fa4ff5e5ac3544557693ba778e00 by web-flow

[FEATURE] add logarithmic scale method for graduated renderer

**Comment by DelazJ** [comment] 2019-09-06 07:50
duplicate of #4192

**Closed by DelazJ** 2019-09-06 07:50 UTC
Labels: Automatic new feature
