### ISSUE TITLE
Merge pull request #3690 from nyalldawson/extract_by_exp

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1484] opened 2016-10-29 22:23 UTC
Original commit: https://github.com/qgis/QGIS/commit/c494c472ac2bef48dcf6d63b34d249bbcc1a49e0 by web-flow

[FEATURE][processing] New extract by expression algorithm

**Comment by DelazJ** [comment] 2016-10-30 15:11
duplicate of #1483

**Closed by DelazJ** 2016-10-30 15:11 UTC
Labels: Automatic new feature
