### ISSUE TITLE
Merge pull request #4327 from tomkralidis/issue-16320

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1808] opened 2017-04-03 17:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/baced7b7708d450cd5a0dede377e4747f7525133 by web-flow

[FEATURE] [needs-docs] MetaSearch: add support for ESRI MapServer/FeatureServer layer integration (fixes #16320)

**Comment by DelazJ** [comment] 2017-04-03 20:07
duplicate of #1807

**Closed by DelazJ** 2017-04-03 20:07 UTC
Labels: Automatic new feature
