### ISSUE TITLE
[FEATURE] Add an option to show user color schemes menus

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1207] opened 2016-07-21 21:32 UTC
Original commit: https://github.com/qgis/QGIS/commit/12a21474276322084e9c67ad46dd68aa486c34f1 by nyalldawson

This adds the ability for users to set whether a user created
color scheme should show up in the color button drop-down menus.

It's accessed through the color picker dialog, on the lists tab.
Just add a new color scheme, then from the scheme menu tick the
new "show in buttons" option.

Handy if you have sets of common palettes and want them to be
instantly available through the color menu.

**Comment by DelazJ** [comment] 2016-08-10 12:09
duplicate of #1208

**Closed by DelazJ** 2016-08-10 12:09 UTC
Labels: Automatic new feature
