### ISSUE TITLE
Merge pull request #7194 from wonder-sk/snap-geometries-alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3013] opened 2018-09-14 10:36 UTC
Original commit: https://github.com/qgis/QGIS/commit/9bcd21fb19f2bce170f5cdab4ccdcf53e4c04487 by web-flow

[FEATURE] Snap geometries algorithm

**Comment by DelazJ** [comment] 2018-09-14 10:50
Duplicate of #3012

**Closed by DelazJ** 2018-09-14 10:50 UTC
Labels: Automatic new feature
