### ISSUE TITLE
Training data repository issue for training manual QGIS 3.10

### ISSUE THREAD

**Issue by simone100** [qgis/QGIS-Documentation#5726] opened 2020-06-18 12:52 UTC
## Description

I am working with training dataset QGIS 3.10, but the training often is inconsistent with the downloaded data. The vector which the documentation refer sometimes have the same name but the field are different and more. 
Other issue: it tells me to go to load a shapefile from the dataset (for example road.shp and building.shp, but there is no shapefile vector for these feature inside the training dataset. I realized after that it was a inside the geopackage called training data.

Is it our problem or I do someting wrong? 

Page URL: "training data repository" that I find inconsistent with the manual https://docs.qgis.org/3.10/it/docs/training_manual/foreword/intro.html

**Comment by DelazJ** [comment] 2020-06-18 13:07
@simone100 Thanks for reporting. Can you please point to the section where the road.shp and building.shp are mentioned (as data in the shapefile folder)?

**Comment by DelazJ** [comment] 2020-06-18 13:19
> The vector which the documentation refer sometimes have the same name but the field are different and more.

I'm afraid that this is too vague to motivate someone go through the dataset to find the culprit mentions. Please provide detailed information on what is missing (the layer and wrong field, the url of the section) so that we efficiently fix the issue. Thanks.

**Comment by DelazJ** [comment] 2020-06-18 13:25
ORiginal author: @simone100 at https://github.com/qgis/QGIS-Documentation/issues/5727

## Description


When I follow the training manual I find inconsistence with my qgis version. For example I have the version QGIS 3.10, but the training manual show screenshot of dialog that does not correspond to mine. 
For example: look at the pictures with two example that compare the manual and what I can see with my version QGIS 3.10!
![QGIS](https://user-images.githubusercontent.com/51158026/85024524-7bd47580-b176-11ea-86a7-645b7b7b4e3b.png)

Did I something wrong with the installation or the manual uses screenshot from other versions?


Page URL: https://docs.qgis.org/3.10/en/docs/training_manual/vector_classification/classification.html

**Comment by simone100** [comment] 2020-06-18 13:43
It is my mistake for one issues!
"Use the steps learnt in Create a Map lesson to add ESRI Shapefiles roads.shp and buildings.shp as layers to the current project. "
https://docs.qgis.org/3.10/en/docs/training_manual/introduction/mapviewnavigation.html

But it refers to:
2.1.2.  Try Yourself
Repeat the steps above to add the places.shp and rivers.shp layers from the same folder (exercise_data/shapefile) to the map.
https://docs.qgis.org/3.10/en/docs/training_manual/introduction/preparation.html
So for this no problem!!





But there is still this issue, my landuse.shp has more field than the tutorial in 4.3.1  (right my features, left features of the tutorial)
https://docs.qgis.org/3.10/en/docs/training_manual/vector_classification/classification.html

![QGIS2png](https://user-images.githubusercontent.com/51158026/85026386-e7b7dd80-b178-11ea-9bd4-7af3183b3af3.png)

and different features (right my features, left feature of the tutorial)
![QGIS4](https://user-images.githubusercontent.com/51158026/85027244-fd79d280-b179-11ea-92e3-899895342949.png)

**Comment by DelazJ** [comment] 2020-06-18 14:05
If you check with the [testing documentation](https://docs.qgis.org/testing/en/docs/training_manual/index.html), are your data and screenshots inline with that doc?

**Comment by simone100** [comment] 2020-06-18 14:12
> If you check with the testing documentation, are your data and screenshots inline with that doc?

Yes if I rapidly overlook at that,  but before I did not take testing as tutorial because I read "testing" and I did not trust. Do you suggest following testing for all exercises?

**Comment by DelazJ** [comment] 2020-06-18 14:34
The issue is that there are some changes we did recently and we (actually I) had to backport and could not do on time. will try to look at it tonight. So 3.10 should be fine, once we rebuild the docs (tomorrow or the day after).
In the meantime you can use testing. Testing does not mean it's in test, it's just how we call anything that is more recent than the last LTR (ie, it's currently targeting 3.12, 3.14... but these versions look more like 3.10, so should be fine, compared to what is in the 3.10 docs which is from earlier versions)

**Comment by simone100** [comment] 2020-06-18 14:36
ok, tank you very much!

**Comment by jveenstra1** [comment] 2020-06-22 15:45
Hi! I'm working through the tutorial as well.  I started using the testing version after reading through this thread, but there is still and issue with the instructions:

"Use the steps learnt in Create a Map lesson to add ESRI Shapefiles roads.shp and buildings.shp as layers to the current project. "
https://docs.qgis.org/testing/en/docs/training_manual/introduction/mapviewnavigation.html#basic-fa-basic-navigation-tools

The buildings.shp, and roads.shp are not in the shapefiles folder.  These instructions would be very confusing for a beginner.  

I found them in the training_data.gpkg, but a new user would not know to look there.
Additional instructions would be needed.
Thanks!

**Comment by havatv** [comment] 2020-06-22 16:23
> Hi! I'm working through the tutorial as well. I started using the testing version after reading through this thread, but there is still and issue with the instructions:
> 
> "Use the steps learnt in Create a Map lesson to add ESRI Shapefiles roads.shp and buildings.shp as layers to the current project. "
> https://docs.qgis.org/testing/en/docs/training_manual/introduction/mapviewnavigation.html#basic-fa-basic-navigation-tools
> 
> The buildings.shp, and roads.shp are not in the shapefiles folder. These instructions would be very confusing for a beginner.
> 
> I found them in the training_data.gpkg, but a new user would not know to look there.
> Additional instructions would be needed.
> Thanks!

Thanks for reporting!
This should hopefully be fixed when #5748 is merged.

**Comment by havatv** [comment] 2020-06-22 23:45
Only partly fixed, so reopening.

**Comment by DelazJ** [comment] 2020-11-10 21:48
Should be fixed since #5767

**Closed by DelazJ** 2020-11-10 21:48 UTC
Labels: Training Manual
