### ISSUE TITLE
[processing][FEATURE] Add "Save Log to File" algorithm for models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5188] opened 2020-03-31 09:35 UTC
Original commit: https://github.com/qgis/QGIS/commit/60af337c3cfdad7e0aae5838f580ab8fa493f510 by nyalldawson

This algorithm saves the contents of the execution log (right up to
the point in the model at which the 'save log' algorithm executes)
to a file.

It can be used to automatically store the debugging log when running
models for later reference and transparency.

**Comment by DelazJ** [comment] 2020-03-31 18:03
Duplicate of #5189

**Closed by DelazJ** 2020-03-31 18:03 UTC
Labels: 3.14, Automatic new feature
