### ISSUE TITLE
Merge pull request #3665 from rouault/save_style_gpkg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1470] opened 2016-10-26 09:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/2d2ce00341a976a856be24e6981cb2c5ea031679 by web-flow

 [FEATURE] [OGR provider] Load/save style in database for GPKG and Spatialite

**Comment by DelazJ** [comment] 2016-10-26 18:35
duplicate of #1469

**Closed by DelazJ** 2016-10-26 18:35 UTC
Labels: Automatic new feature
