### ISSUE TITLE
[needs-docs] [labeling] Allow data defined control over line placement options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3851] opened 2019-06-20 03:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/3bd3aba25b60f32c2170e519a5e9b37249d49be2 by nirvn

Allows users to override the line placement settings (e.g.
above/below/on line options) on a per-feature basis. Somehow
this one was the only(?) setting from labeling which
was missing a data defined control...

**Comment by DelazJ** [comment] 2019-06-20 08:16
Duplicate of #3852

**Closed by DelazJ** 2019-06-20 08:16 UTC
Labels: Automatic new feature
