### ISSUE TITLE
[FEATURE] Substitution list support for labeling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1359] opened 2016-08-29 22:46 UTC
Original commit: https://github.com/qgis/QGIS/commit/46fba7ce80039d5feb8445410ddf98e485f5951f by nyalldawson

Adds the ability to specify a list of text substitutes to make
which apply to label text. Eg abbrevating street types.

Users can export and import lists of substitutes to make
reuse and sharing easier.

**Comment by DelazJ** [comment] 2016-08-30 11:04
duplicate of #1361

**Closed by DelazJ** 2016-08-30 11:04 UTC
Labels: Automatic new feature
