### ISSUE TITLE
Merge pull request #34654 from elpaso/vectorlayertools-suppress-form-popup

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4943] opened 2020-02-27 07:11 UTC
Original commit: https://github.com/qgis/QGIS/commit/c90fbd59784d04a93bec28d21b7864dd56f12f42 by web-flow

[feature] Relation widget force suppress popup

**Comment by DelazJ** [comment] 2020-02-27 07:36
Duplicate of #4942

**Closed by DelazJ** 2020-02-27 07:36 UTC
Labels: 3.12, Automatic new feature
