### ISSUE TITLE
QGIS 3,22.1 version

### ISSUE THREAD

**Issue by eboelcke** [qgis/QGIS-Documentation#7280] opened 2022-01-12 16:32 UTC
## Description
There are several parts of the training manual that are obsolete in QGIS 3.22.1 version As an example, the raster georeferencer has been changed and it is hard for inexperienced GIS users following the text as it is, to figure out the right procedure. I strongly recommend either to produce a current version of the manual, or at least, incorporate the innovations so the reader may follow them.

**Comment by roya0045** [comment] 2022-01-12 16:45
You are welcome to contribute to anything that is lacking if you want things to change rapidly. The changes to the georeferencer should be out soon.

**Comment by DelazJ** [comment] 2022-01-13 10:08
> There are several parts of the training manual that are obsolete in QGIS 3.22.1 version

Unfortunately true
> As an example, the raster georeferencer has been changed and it is hard for inexperienced GIS users following the text as it is, to figure out the right procedure.

This example isn't one. At all. If you don't tell us **what exactly** puzzles you in the updated description, there's almost zero chance it gets fixed one day.
> I **strongly** recommend either to produce a current version of the manual, or at least, incorporate the innovations so the reader may follow them.

I also strongly wished that more people hit the "Edit on github" button at the top of each page to help fix issues they find than just reporting it and let the workload on the very few people contributing to the docs.
That said, I'm not sure I understand the distinction between the two options you propose. Wouldn't incorporating the innovations lead to an updated version?
Last but not the least, given the pace QGIS evolves and the low manpower, it'll be impossible to ensure every exercice in the training manual is up to date (we had updated a great number for 3.10 or 3.16). It has been decided that the focus should prioritarily be on the user manual and cookbook. Not training manual, unless someone has free time (that I spent the other day on your #7270)

**Comment by eboelcke** [comment] 2022-01-13 16:32
I am sorry you are so sensitive to my suggestions and I really apologize for disturbing you.All of your reasons are more than reasonable and should be taken into account. On the other hand, I suppose you as an experienced participant in the QGIS project may understand that a beginner like me gets puzzled and frustrated when the software doesn’t work as expected. – As described in the manual. Also I supposed that you may realize that when I mentioned the raster georeferencer issue I was referring to “waiting to enter the CRS when asked for”  when the plugin o whatever it is has been changed and has incorporated a field to enter the CRS at the point entry form. I took me, -should recognize not the most brilliant mind – one full day of trials to find the right answer. With regards to the distinction between the options I proposed is that: in one adding a note or comment referring to the newest version has the advantage to cover old and new versions and not demanding to much labor;  the other is to produce a brand new document for the new version. Yes, it is true, you may argue that the manual with the inclusions is a new manual.I also like to offer my help for whatever may be of use to update this manual. My first thought was that being a GIS beginner it was very little what I could offer, and that the right way to go is to left the task to experienced people. Anyhow, at this regard, I can offer to look into the raster georeferencer issue and also into the lack of the “map units” option at the snapping options forms to begin with. I’d appreciate if you direct me on how and where to face this task.Finally, I’d like to thank you and all the other contributors to provide us with such an excellent tool as QGIS and I’m really sorry to know you’re not getting all the help you need.E. Boelcke  From: Harrissou Sant-annaSent: Thursday, January 13, 2022 7:08 AMTo: qgis/QGIS-DocumentationCc: eboelcke; AuthorSubject: Re: [qgis/QGIS-Documentation] QGIS 3,22.1 version (Issue #7begginer like me get280) There are several parts of the training manual that are obsolete in QGIS 3.22.1 versionUnfortunately trueAs an example, the raster georeferencer has been changed and it is hard for inexperienced GIS users following the text as it is, to figure out the right procedure.This example isn't one. At all. If you don't tell us what exactly puzzles you in the updated description, there's almost zero chance it gets fixed one day.I strongly recommend either to produce a current version of the manual, or at least, incorporate the innovations so the reader may follow them.I also strongly wished that more people hit the "Edit on github" button at the top of each page to help fix issues they find than just reporting it and let the workload on the very few people contributing to the docs.That said, I'm not sure I understand the distinction between the two options you propose. Wouldn't incorporating the innovations lead to an updated version?Last but not the least, given the pace QGIS evolves and the low manpower, it'll be impossible to ensure every exercice in the training manual is up to date (we had updated a great number for 3.10 or 3.16). It has been decided that the focus should prioritarily be on the user manual and cookbook. Not training manual, unless someone has free time (that I spent the other day on your #7270)—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by DelazJ** [comment] 2022-01-14 23:49
@eboelcke sorry if I've been rude. It's just that everybody have ideas of what should be good or done for the docs, this and that but when you make a call for reviewers and you get almost no reaction... it is just frustrating and disappointing... But, not your fault and you didn't deserve it. Sorry.
> Also I supposed that you may realize that when I mentioned the raster georeferencer issue I was referring to “waiting to enter the CRS when asked for”  when the plugin o whatever it is has been changed and has incorporated a field to enter the CRS at the point entry form. 

Sorry but no! It's not obvious. We can't go through every exercise when there's a report. You, doing the exercise, know the context and issues better than us at that moment. So the better the issue is described, the happier everyone is.
And I even didn't notice that change in the widget. Fix in #7284 (feel free to comment if something is missing/wrong).
> I also like to offer my help for whatever may be of use to update this manual. My first thought was that being a GIS beginner it was very little what I could offer, and that the right way to go is to left the task to experienced people.

Reporting issues is a very good start (let's just avoid *strong recommendation* :smiley: ). Thanks.
If it's clear for you that there's an issue and you know the fix, don't wait for anyone else, open a pull request with your changes and you'll find someone to review (TBH it may be quicker most of the times).
You can find instructions at https://docs.qgis.org/latest/en/docs/documentation_guidelines/first_contribution.html and I can be available by the end of next week if you need more help. Maybe could you open dedicated reports for the issues you met (check first it's not already reported, please).
> Finally, I’d like to thank you and all the other contributors to provide us with such an excellent tool as QGIS

Thank you. And thank you for using it and willing to help us improve it...

**Comment by eboelcke** [comment] 2022-01-15 21:13
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
@font-face
	{font-family:"Segoe UI Emoji";
	panose-1:2 11 5 2 4 2 4 2 2 3;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0in;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:8.5in 11.0in;
	margin:1.0in 1.0in 1.0in 1.0in;}
div.WordSection1
	{page:WordSection1;}
***@***.*** Sant-anna No hard feelings. Sent from Mail for Windows From: Harrissou Sant-annaSent: Friday, January 14, 2022 8:49 PMTo: qgis/QGIS-DocumentationCc: eboelcke; MentionSubject: Re: [qgis/QGIS-Documentation] QGIS 3,22.1 version (Issue ***@***.*** sorry if I've been rude. It's just that everybody have ideas of what should be good or done for the docs, this and that but when you make a call for reviewers and you get almost no reaction... it is just frustrating and disappointing... But, not your fault and you didn't deserve it. Sorry.Also I supposed that you may realize that when I mentioned the raster georeferencer issue I was referring to “waiting to enter the CRS when asked for” when the plugin o whatever it is has been changed and has incorporated a field to enter the CRS at the point entry form.Sorry but no! It's not obvious. We can't go through every exercise when there's a report. You, doing the exercise, know the context and issues better than us at that moment. So the better the issue is described, the happier everyone is.And I even didn't notice that change in the widget. Fix in #7284 (feel free to comment if something is missing/wrong).I also like to offer my help for whatever may be of use to update this manual. My first thought was that being a GIS beginner it was very little what I could offer, and that the right way to go is to left the task to experienced people.Reporting issues is a very good start (let's just avoid strong recommendation 😃 ). Thanks.If it's clear for you that there's an issue and you know the fix, don't wait for anyone else, open a pull request with your changes and you'll find someone to review (TBH it may be quicker most of the times).You can find instructions at https://docs.qgis.org/latest/en/docs/documentation_guidelines/first_contribution.html and I can be available by the end of next week if you need more help. Maybe could you open dedicated reports for the issues you met (check first it's not already reported, please).Finally, I’d like to thank you and all the other contributors to provide us with such an excellent tool as QGISThank you. And thank you for using it and willing to help us improve it...—Reply to this email directly, view it on GitHub, or unsubscribe.Triage notifications on the go with GitHub Mobile for iOS or Android. You are receiving this because you were mentioned.Message ID: ***@***.***>

**Closed** 2022-01-20 13:53 UTC
Labels: Training Manual
