### ISSUE TITLE
Move value group box under help area [Expression builder] [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3235] opened 2018-12-10 12:18 UTC
Original commit: https://github.com/qgis/QGIS/commit/44d1d10eb35f7f40a268f95573710885b7d23b4c by web-flow

move value group box under help area [Expression builder] [needs-docs]

**Comment by DelazJ** [comment] 2018-12-12 15:39
Duplicate of #3247

**Closed by DelazJ** 2018-12-12 15:39 UTC
Labels: Automatic new feature
