### ISSUE TITLE
[needs-docs] Fix parameter's label and some distance default value

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2938] opened 2018-08-31 00:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/5bb7818b477bd964de93f45d96b6b0a2619e8a9a by nyalldawson

more coherent with meters

(cherry picked from commit 00b0e3b0bc683297850dae04d7e1a3f386210589)

**Comment by DelazJ** [comment] 2018-08-31 07:41
Duplicate of #2935

**Closed by DelazJ** 2018-08-31 07:41 UTC
Labels: Automatic new feature
