### ISSUE TITLE
 [FEATURE] possibility to set a maximum marker size in layout legend

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5813] opened 2020-07-03 11:06 UTC
Original commit: https://github.com/qgis/QGIS/commit/f0ad33c8a9482a515d690d4d1f0e165af80ab0ca by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-07-03 11:56
Duplicate of #5814

**Closed by DelazJ** 2020-07-03 11:56 UTC
Labels: 3.16, Automatic new feature
