### ISSUE TITLE
Add a hint in the description of qgis_process

### ISSUE THREAD

**Issue by mhaelsig** [qgis/QGIS-Documentation#7947] opened 2023-01-08 17:12 UTC
## Description
I would include a hint  in the description of qgis_process:
'If you use qgis_process on a system without window manager (e.g. a headless server), you should set 

> **export QT_QPA_PLATFORM=offscreen** 

before calling qgis_process.
Page URL:
https://docs.qgis.org/testing/en/docs/user_manual/processing/standalone.html?highlight=qgis_process

[Otherwise qgis_process throws the error message:
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.]

**Comment by DelazJ** [comment] 2023-01-09 15:22
@m-kuhn @nyalldawson May I have your opinion here, please: if it's correct and if it is something that should be addressed in our docs, or not? Thanks

**Comment by m-kuhn** [comment] 2023-01-09 16:23
That is a great hint which is correct and could be added to the docs.
AFAICT it's an alternative to `xvfb-run` which is more lightweight and probably should replace it also in other parts like QGIS server.

**Comment by nyalldawson** [comment] 2023-01-09 20:08
@m-kuhn should we hardcode that env variable to offscreen in qgis_process? 


There's absolutely no time we should ever allow a UI to be shown for qgis_process...

**Comment by m-kuhn** [comment] 2023-01-09 21:35
I think it's only available on linux

**Comment by nyalldawson** [comment] 2023-01-09 22:17
@m-kuhn does it hurt to set for other platforms? Seems we do this for server: https://github.com/qgis/QGIS/blob/master/src/server/qgis_map_serv.cpp#L70 (although it has a note in there that printing capabilities are disabled... not sure if that's outdated information. There's zero qt docs on what "offscreen" actually means...)

**Comment by nyalldawson** [comment] 2023-01-09 22:19
Actually there's lots of discussion here: https://github.com/qgis/QGIS/pull/5413

**Comment by nyalldawson** [comment] 2023-01-09 22:24
So what I'm thinking now:

- we implement the same logic as server does in https://github.com/qgis/QGIS/blob/master/src/server/qgis_map_serv.cpp#L70 
- we add a new flag for algorithms "requires display server", which we set for the various layout/html rendering related algorithms
- if the flag is present for the algorithm and QT_QPA_PLATFORM is set to offscreen, we raise a descriptive friendly error message and abort

(we could possibly go even more fine-grained if the issue is only relating to webkit renders and only raise the error when a layout html item is present, but for a first step raising the warning for all layout algorithms would still be a good move forward...)

Thoughts @m-kuhn ?

**Comment by m-kuhn** [comment] 2023-01-09 22:27
Did you try if it still crashes with html? It would be nice if we'd get away without this extra effort.
Other than that this sounds good 👍

**Comment by mhaelsig** [comment] 2023-10-19 10:05
I tested with qgis_process 3.32.3-Lima on a headless Debian 12 (bookworm) server (files attached). 
qgis_process calls the algorithm 'printlayouttopdf'. The print layout includes a simple HTML (bold). The PDF is generated as expected.
[The QGIS-Server 3.32 on the same system also generates PDF-prints, controlled by qwc2]
Therefore, I would stay at least with the light weight solution 'export QT_QPA_PLATFORM=offscreen', as proposed, in the doumentation.  A next step could be to include this in qgis_process, as described above.

[test_print.zip](https://github.com/qgis/QGIS-Documentation/files/13040677/test_print.zip)

**Closed** 2023-11-05 07:19 UTC
Labels: Processing
