### ISSUE TITLE
Merge pull request #8627 from m-kuhn/represent_class_values

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3245] opened 2018-12-11 15:44 UTC
Original commit: https://github.com/qgis/QGIS/commit/4e38193bf382e3bae7764a2daf4a8a74342b5c71 by web-flow

Use represention values for classified renderers [FEATURE]

**Comment by DelazJ** [comment] 2018-12-11 15:48
Duplicate of #3244

**Closed by DelazJ** 2018-12-11 15:48 UTC
Labels: Automatic new feature
