### ISSUE TITLE
Merge pull request #7626 from rudivs/kneighbour

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3019] opened 2018-09-14 13:32 UTC
Original commit: https://github.com/qgis/QGIS/commit/8b07b4ed9e5072ea7e4b85b41d041385e21a826f by web-flow

[feature] Adapted k-neighbour concave hull plugin as QGIS 3 algorithm

**Comment by DelazJ** [comment] 2018-09-14 13:36
duplicate of #3018

**Closed by DelazJ** 2018-09-14 13:36 UTC
Labels: Automatic new feature
