### ISSUE TITLE
[FEATURE] Label polygons using curved labels along perimeter

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1210] opened 2016-07-27 04:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/5f33991e7bcd95069ba88e01cafa7078bbad5f24 by nyalldawson

This adds a new mode for labeling polygons, where the perimeter
of the polygon is labeled using curved labeling.

**Comment by DelazJ** [comment] 2016-08-10 12:16
duplicate of #1273

**Closed by DelazJ** 2016-08-10 12:16 UTC
Labels: Automatic new feature
