### ISSUE TITLE
QGIS UNEXPECTEDLY ENDED

### ISSUE THREAD

**Issue by agronomys** [qgis/QGIS-Documentation#9311] opened 2024-10-21 16:29 UTC
## Description
Crash ID: [4b13efe123793dfa5c0f46af6df67731fc6de8e3](https://github.com/qgis/QGIS/search?q=4b13efe123793dfa5c0f46af6df67731fc6de8e3&type=Issues)

Stack Trace

memcpy_repmovs memcpy.asm:114
CPLStringList::empty :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
CPLStringList::PartialFindString :
CPLStringList::empty :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsArchive::zip :
QgsImageOperation::overlayColor :
QgsImageOperation::flipImage :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.10-A Coru�a
QGIS code revision: 8b051b9a43
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

**Comment by DelazJ** [comment] 2024-10-21 18:55
Hi @agronomys ,
This repository is dedicated to [QGIS documentation](https://docs.qgis.org) issues, not for the application issues that should be reported in their [issue tracker](https://github.com/qgis/QGIS/issues). You'd need to provide more details on what you were expecting/doing before crashes. Also, try running QGIS with [a clean profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) to see whether the issue is reproducible.
Furthermore, I see that you are running QGIS 3.10 which is not maintained for years. You'd need an upgrade before any report to the above issue tracker.

I'm closing. Thanks

**Closed by DelazJ** 2024-10-21 18:55 UTC
