### ISSUE TITLE
Merge pull request #8612 from elpaso/vector-legend-toggle-items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3228] opened 2018-12-07 08:36 UTC
Original commit: https://github.com/qgis/QGIS/commit/16922a304183d5bd7952b45a11f3115a1a33c845 by web-flow

Add a toggle action to vector layer legend items [feature]

**Comment by DelazJ** [comment] 2018-12-07 09:01
Duplicate of #3227

**Closed by DelazJ** 2018-12-07 09:01 UTC
Labels: Automatic new feature
