### ISSUE TITLE
Merge pull request #4970 from andreasneumann/array_reverse

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2028] opened 2017-08-05 21:09 UTC
Original commit: https://github.com/qgis/QGIS/commit/736d732912e603ee7cc38ad6b81402eb594b05be by web-flow

[FEATURE] expression function array_reverse

**Comment by DelazJ** [comment] 2017-08-06 21:31
Duplicate of #2027

**Closed by DelazJ** 2017-08-06 21:31 UTC
Labels: Automatic new feature
