### ISSUE TITLE
[needs-docs] Revise QgsPathResolver::setPathPreprocessor API

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4125] opened 2019-08-22 20:35 UTC
Original commit: https://github.com/qgis/QGIS/commit/24fb1196c5b76c6721fda2f6ee25bfa385926cb2 by nyalldawson

Allow path preprocessors to be chained and don't force replace
any existing ones.

Processors can be removed via a call to QgsPathResolver::removePathPreprocessor,
using the unique ID returned by the original call to setPathPreprocessor

**Comment by DelazJ** [comment] 2019-08-23 05:13
Duplicate of #4130

**Closed by DelazJ** 2019-08-23 05:13 UTC
Labels: Automatic new feature, PyQGIS Cookbook
