### ISSUE TITLE
[MetaSearch] OWS GetCapabilities checking regression (fixes #19787) [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3428] opened 2019-02-05 03:10 UTC
Original commit: https://github.com/qgis/QGIS/commit/23294590c94bf8124d381afa30089a0b7b4fd252 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment] 2019-02-05 07:58
Duplicate of #3426. Closing.

**Closed by havatv** 2019-02-05 07:58 UTC
Labels: Automatic new feature
