### ISSUE TITLE
Merge pull request #3670 from nirvn/expression_replace_array

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1473] opened 2016-10-27 05:15 UTC
Original commit: https://github.com/qgis/QGIS/commit/1d09538c5cf1ee5d9bb195c1aeb4f0a1c1cc9bd2 by web-flow

[FEATURE] array support for the replace() expression function

**Comment by DelazJ** [comment] 2016-10-27 11:50
duplicate of #1472

**Closed by DelazJ** 2016-10-27 11:50 UTC
Labels: Automatic new feature
