### ISSUE TITLE
[FEATURE][processing] Remember parameter values between model designer runs

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4965] opened 2020-03-06 08:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/2a1bf56493ba1373fcccadff489e28d584a52c64 by nyalldawson

When designing a model, users typically will need to run the model
many times as they tweak its structure.

This change causes the parameters used when running the model from
the designer to be remembered and saved into the model, so that
each time you run the model from the designer you don't have to
re-set all the input parameter values to the desired test ones.

Makes iterative model design SO much easier!

Sponsored by Alta Ehf

**Comment by DelazJ** [comment] 2020-03-06 08:49
Duplicate of #4966

**Closed by DelazJ** 2020-03-06 08:49 UTC
Labels: 3.12, Automatic new feature
