### ISSUE TITLE
Merge pull request #7170 from rouault/wfs_pagesize

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2728] opened 2018-06-22 12:57 UTC
Original commit: https://github.com/qgis/QGIS/commit/14a913e25b52aeb956f0f2838e693e08acddf646 by web-flow

[WFS provider] [FEATURE] Allow user to enable/disable paging and specify page size (fixes #18935)

**Comment by DelazJ** [comment] 2018-06-22 13:32
Duplicate of #2727

**Closed by DelazJ** 2018-06-22 13:32 UTC
Labels: Automatic new feature
