### ISSUE TITLE
Merge pull request #4231 from nyalldawson/options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1745] opened 2017-03-08 22:18 UTC
Original commit: https://github.com/qgis/QGIS/commit/94bef531f0371141e1e83ddcc5bfe2e71b2c6438 by web-flow

[FEATURE] Interface for plugins to embed pages in the options dialog

**Comment by DelazJ** [comment] 2017-03-09 10:54
Duplicate of #1743

**Closed by DelazJ** 2017-03-09 10:54 UTC
Labels: Automatic new feature
