### ISSUE TITLE
Merge pull request #3450 from nyalldawson/smoooooth

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1377] opened 2016-09-02 23:38 UTC
Original commit: https://github.com/qgis/QGIS/commit/8107856cc5844eafb20892d8fafa5affc314e62a by web-flow

[FEATURE] Extra control when smoothing geometries

**Comment by DelazJ** [comment] 2016-09-04 10:10
duplicate of #1376

**Closed by DelazJ** 2016-09-04 10:10 UTC
Labels: Automatic new feature
