### ISSUE TITLE
[FEATURE] Allow rendering raster layers outside the reported extent

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4029] opened 2019-07-25 08:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/a681e1ed4542f70d8c966c2d5a3b94c2ca0e5e48 by web-flow

[FEATURE] Allow rendering raster layers outside the reported extent

**Comment by DelazJ** [comment] 2019-08-23 06:35
Duplicate of #4028

**Closed** 2019-12-15 09:03 UTC
Labels: 3.10, Automatic new feature
