### ISSUE TITLE
[processing][needs-docs] native vector split algorithm now outputs
GeoPackages instead of shapefiles (refs #20557)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3412] opened 2019-01-29 15:35 UTC
Original commit: https://github.com/qgis/QGIS/commit/a9466cd097b05b6c863dd71f50c6262cd208647b by nyalldawson

Also remove default output extension Processing settings as they are not
used anymore.

(cherry picked from commit 8446d3bdf0089cdee6316e40a7cd0047dbf455c1)

**Comment by havatv** [comment] 2019-01-29 15:41
Duplicate of #3409.

**Closed by havatv** 2019-01-29 15:41 UTC
Labels: Automatic new feature
