### ISSUE TITLE
Merge pull request #38405 from olivierdalang/refFunctionsRebase

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6101] opened 2020-09-11 13:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/a46acb416976c8eae0e2b8be2f4ac1ff10a0883b by web-flow

[feature][expression] refFunction port to core

**Comment by DelazJ** [comment] 2020-09-11 14:04
Duplicate of #6102

**Closed by DelazJ** 2020-09-11 14:04 UTC
Labels: 3.14, Automatic new feature
