### ISSUE TITLE
Merge pull request #34760 from elpaso/relation-reference-add-checkbox-to-hide-save-child-edits-button

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4947] opened 2020-02-28 14:52 UTC
Original commit: https://github.com/qgis/QGIS/commit/1978cb9b8ac73a8506a8a13e028d38c87802af91 by web-flow

[feature] Relation wdgt: add checkbox to hide save child edits button

**Comment by DelazJ** [comment] 2020-02-28 15:05
Duplicate of #4946

**Closed by DelazJ** 2020-02-28 15:05 UTC
Labels: 3.12, Automatic new feature
