### ISSUE TITLE
[FEATURE] Make processing dissolve algorithm accept multiple fields

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1232] opened 2016-08-02 04:45 UTC
Original commit: https://github.com/qgis/QGIS/commit/bb54b4f41a726737d5d28a71632ed29a9a8045df by nyalldawson

This allows you to dissolve based on more than one field value

**Comment by DelazJ** [comment] 2017-05-06 16:02
duplicate of #1275

**Closed by DelazJ** 2017-05-06 16:02 UTC
Labels: Automatic new feature, Processing
