### ISSUE TITLE
[needs-docs][ui] Better placement for the method combobox and auto open action

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4764] opened 2020-01-10 08:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/e99cef48ca1c8f036149d261bc68e352b66a43ba by nirvn

(this is a follow up to PR #33643) better combobox / checkbox placement

**Comment by DelazJ** [comment] 2020-01-13 14:23
Duplicate of #4769

**Closed by DelazJ** 2020-01-13 14:23 UTC
Labels: 3.12, Automatic new feature
