### ISSUE TITLE
[FEATURE][layouts] Allow layout attribute tables to be styled using the foreground
and background colors of matching conditional styles attached to the layer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4750] opened 2020-01-08 02:31 UTC
Original commit: https://github.com/qgis/QGIS/commit/400e3dace1cabc7656bc57678ec81df2053e76d7 by nyalldawson

When the new "Apply layer conditional styling colors" option is enabled in the
layout attribute table settings, any conditional styling rules present in the
layer will be applied inside the layout attribute table (foreground and
background colors only, for now!).

Refs #25712

Sponsored by City of Canning

**Comment by DelazJ** [comment] 2020-01-08 13:09
Duplicate of #4751

**Closed by DelazJ** 2020-01-08 13:09 UTC
Labels: 3.12, Automatic new feature
