### ISSUE TITLE
Merge pull request #4522 from nyalldawson/new_random

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1897] opened 2017-05-09 04:34 UTC
Original commit: https://github.com/qgis/QGIS/commit/592fcfa74b24a1e67a12de1179300fa6dfb41e40 by web-flow

[needs-docs] Add a "shuffle random" option to color ramp button

**Comment by DelazJ** [comment] 2017-05-09 10:58
duplicate of #1896

**Closed by DelazJ** 2017-05-09 10:58 UTC
Labels: Automatic new feature
