### ISSUE TITLE
[Feature][PostgreSQL] Tests: Compile expression functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1606] opened 2017-01-02 16:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/4bc06b18e957dc728a2f6c3821c8caf210f28e64 by rldhont

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2017-01-02 16:25
duplicate of #1605

**Closed by DelazJ** 2017-01-02 16:25 UTC
Labels: Automatic new feature
