### ISSUE TITLE
Merge pull request #4643 from merkato/master

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2726] opened 2018-06-22 12:47 UTC
Original commit: https://github.com/qgis/QGIS/commit/cbde32f0fce4a5a0b0c472337da49c6841758b4e by web-flow

[FEATURE] Add role logging for PostGIS versioning.

**Comment by DelazJ** [comment] 2018-06-22 13:33
Duplicate of #2725

**Closed by DelazJ** 2018-06-22 13:33 UTC
Labels: Automatic new feature
