### ISSUE TITLE
Merge pull request #7908 from borysiasty/nicer_plugin_links

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3024] opened 2018-09-18 08:13 UTC
Original commit: https://github.com/qgis/QGIS/commit/b5024c32c2fb39dc6b372e47e9800bcd21d735c2 by web-flow

[Plugin manager][needs-docs] More unified links to the installed and available version.

**Comment by DelazJ** [comment] 2018-09-18 09:10
Duplicate of #3023

**Closed by DelazJ** 2018-09-18 09:10 UTC
Labels: Automatic new feature
