### ISSUE TITLE
Merge pull request #6876 from DelazJ/patch-2

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2606] opened 2018-05-07 08:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/dd2eb3a47551b6043c286850f630287be679ddc4 by web-flow

[needs-docs] Rename action in Layers panel contextual menu

**Comment by DelazJ** [comment] 2018-05-07 10:08
Duplicate 
Duplicate of #2605

**Closed by DelazJ** 2018-05-07 10:08 UTC
Labels: Automatic new feature
