### ISSUE TITLE
Merge pull request #37429 from elpaso/server-api-sorting

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5763] opened 2020-06-26 13:50 UTC
Original commit: https://github.com/qgis/QGIS/commit/e712a3351674fee52dbb989f9db73f5bfc4a4cc6 by web-flow

[feature] Server WFS3 api sorting

**Comment by DelazJ** [comment] 2020-06-26 13:51
Duplicate of #5764

**Closed by DelazJ** 2020-06-26 13:51 UTC
Labels: 3.14, Automatic new feature
