### ISSUE TITLE
[processing][needs-docs] Make Find Projection algorithm simpler to use

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3429] opened 2019-02-05 05:55 UTC
Original commit: https://github.com/qgis/QGIS/commit/c6f3d5ff483554e7a338c07b2cb22f38b5bf4d36 by nyalldawson

We no longer require the seperate CRS parameter, because the extent
parameter contains the CRS information itself. This means the algorithm
is simplified to just picking the layer and drawing the desired area
on the canvas.

**Comment by DelazJ** [comment] 2019-02-07 05:39
Duplicate of #3438

**Closed by DelazJ** 2019-02-07 05:39 UTC
Labels: Automatic new feature
