### ISSUE TITLE
[FEATURE] allow to drag'n'drop layer across several QGIS instances

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5416] opened 2020-05-06 14:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/202ae7b01d8b11c768dca57dddfe5182374d9f5a by 3nids

fixes #20467

**Comment by DelazJ** [comment] 2020-05-06 19:55
Duplicate of #5418

**Closed by DelazJ** 2020-05-06 19:55 UTC
Labels: 3.14, Automatic new feature
