### ISSUE TITLE
[FEATURE][processing] Add option to enable automatic snapping to grid
while designer models

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5110] opened 2020-03-23 09:25 UTC
Original commit: https://github.com/qgis/QGIS/commit/4bad25444192eac71c9c10535fb092e5cee495f2 by nyalldawson

If enabled, model component moving or resizing will be automatically
snapped to a grid

**Comment by DelazJ** [comment] 2020-03-31 18:08
Duplicate of #5111

**Closed by DelazJ** 2020-03-31 18:08 UTC
Labels: 3.14, Automatic new feature
