### ISSUE TITLE
[needs-docs] Revise QgsPathResolver::setPathPreprocessor API

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4126] opened 2019-08-22 20:35 UTC
Original commit: https://github.com/qgis/QGIS/commit/1cec1cc8edfd747a5a170f6125f86e9ad2dc4b8f by nyalldawson

Allow path preprocessors to be chained and don't force replace
any existing ones.

Processors can be removed via a call to QgsPathResolver::removePathPreprocessor,
using the unique ID returned by the original call to setPathPreprocessor

**Comment by DelazJ** [comment] 2019-08-22 21:27
Duplicate of #4125

**Closed by DelazJ** 2019-08-22 21:27 UTC
Labels: Automatic new feature
