### ISSUE TITLE
[processing][needs-docs] Adjust status of controls executing an algorithm dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5049] opened 2020-03-18 13:42 UTC
Original commit: https://github.com/qgis/QGIS/commit/01c7cb1814f1f6039ece71e5c61c0d8c0832926b by web-flow

[processing][needs-docs] Adjust status of controls executing an algorithm dialog

**Comment by DelazJ** [comment] 2020-03-31 18:10
Duplicate of #5048

**Closed by DelazJ** 2020-03-31 18:10 UTC
Labels: 3.14, Automatic new feature
