### ISSUE TITLE
Merge pull request #3597 from rouault/saveas_overwrite_append

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1454] opened 2016-10-17 09:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/da0ee8b007f742f14dcbf40d930157c2a47379ff by web-flow

[FEATURE] Vector layer save as: offer file/layer overwriting, new layer creation, feature and field appending

**Comment by DelazJ** [comment] 2016-10-17 12:23
duplicate of #1453

**Closed by DelazJ** 2016-10-17 12:23 UTC
Labels: Automatic new feature
