### ISSUE TITLE
[FEATURE] Mesh 1D Renderer  (#34848)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4987] opened 2020-03-09 04:59 UTC
Original commit: https://github.com/qgis/QGIS/commit/0675c0b6975ed85572786b40ce680a3499acbb9b by web-flow

* MDAL 0.5.90 : support for custom Logger and 1D meshes
* [FEATURE] [MESH] Support rendering of 1D meshes, see https://github.com/qgis/QGIS-Enhancement-Proposals/issues/164

1D mesh consist of edges (edge is straight line segment with 2 vertices) and the data that is defined on either
vertices or edges. Such data can be loaded by MDAL and rendered as mesh layer in QGIS.

**Comment by DelazJ** [comment] 2020-03-09 09:06
Duplicate of #4988

**Closed by DelazJ** 2020-03-09 09:06 UTC
Labels: 3.14, Automatic new feature
