### ISSUE TITLE
[needs-docs] remove Server Search tab from the WMS connections dialog
(fix #25660).

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5352] opened 2020-04-24 18:52 UTC
Original commit: https://github.com/qgis/QGIS/commit/b8c3b0e71f11c53a29432d0556154435b0f3ca34 by nyalldawson

As used catalog does not receive updates for years and we already have
more feature rich search with MetaSearch core plugin.

**Comment by DelazJ** [comment] 2020-04-25 07:40
Duplicate of #5353

**Closed by DelazJ** 2020-04-25 07:40 UTC
Labels: 3.12, Automatic new feature
