### ISSUE TITLE
Merge pull request #35382 from 3nids/dnd-across-qgis-instances

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5417] opened 2020-05-06 14:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/37efb4d598ad93b1e2b64b9d2666aaff1b44d602 by web-flow

[FEATURE] allow to drag'n'drop layer across several QGIS instances

**Comment by DelazJ** [comment] 2020-05-06 19:56
Duplicate of #5418

**Closed by DelazJ** 2020-05-06 19:56 UTC
Labels: 3.14, Automatic new feature
