### ISSUE TITLE
[needs-docs][dbmanager] harmonize icons

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2762] opened 2018-06-29 04:58 UTC
Original commit: https://github.com/qgis/QGIS/commit/bd4500e2cd02f1d735b1aa60161aace20841a096 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2018-06-29 05:22
duplicate of #2761

**Closed by DelazJ** 2018-06-29 05:22 UTC
Labels: Automatic new feature
