### ISSUE TITLE
Merge pull request #3080 from nyalldawson/select_tools

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#1032] opened 2016-05-19 11:20 UTC
Original commit: https://github.com/qgis/QGIS/commit/6bf4b92cb96866f8f397cfcadabafaeb2c78afac by nyalldawson

[FEATURE] Improved map select tool behaviour

**Comment by DelazJ** [comment] 2016-05-19 11:42
duplicate of #1031

**Closed by DelazJ** 2016-05-19 11:42 UTC
Labels: Automatic new feature
