### ISSUE TITLE
Merge pull request #6983 from PeterPetrik/qgsquick_2_scalebar_messagelog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2643] opened 2018-05-17 00:37 UTC
Original commit: https://github.com/qgis/QGIS/commit/9a79fc78aa20e92546ef4c2e2f6705701e4c9981 by web-flow

[feature] Add ScaleBar and MessageLog components to QgsQuick library.

**Comment by DelazJ** [comment] 2018-05-17 06:02
duplicate of #2642

**Closed by DelazJ** 2018-05-17 06:02 UTC
Labels: Automatic new feature
