### ISSUE TITLE
Merge pull request #4174 from nyalldawson/stroke

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1713] opened 2017-02-22 09:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/49114aea274a463fcc7135d945b9eeb786b8737a by web-flow

[needs-docs] Rename Outline and Border -> Stroke

**Comment by DelazJ** [comment] 2017-02-22 10:05
duplicate of #1712

**Closed by DelazJ** 2017-02-22 10:05 UTC
Labels: Automatic new feature
