### ISSUE TITLE
[needs-docs][ui] UI/UX revamp of the 3D map configuration dialog (#39448)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6198] opened 2020-10-18 15:10 UTC
Original commit: https://github.com/qgis/QGIS/commit/2626ad61304a0ee88487167c27c78f9f0abd4636 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-10-19 06:04
Duplicate of #6199

**Closed by DelazJ** 2020-10-19 06:04 UTC
Labels: 3.14, Automatic new feature
