### ISSUE TITLE
Merge pull request #4587 from alexbruy/processing-saga

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1918] opened 2017-05-19 12:08 UTC
Original commit: https://github.com/qgis/QGIS/commit/bbcc8725fc2937f560402ea31b3dc58bf1370baf by web-flow

[processing][needs-docs] always use SAGA shipped with QGIS (refs #16422)

**Comment by DelazJ** [comment] 2017-05-19 12:19
duplicate of #1917

**Closed by DelazJ** 2017-05-19 12:19 UTC
Labels: Automatic new feature
