### ISSUE TITLE
Merge pull request #32813 from elpaso/bugfix-gh32809-delete-pg-raster-from-browser

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4407] opened 2019-11-13 10:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/b9a5b826533d79e5c07cfd9fcc5aee4959380590 by web-flow

[feature] Delete PG rasters from browser

**Comment by DelazJ** [comment] 2019-11-13 10:49
Duplicate of #4406

**Closed by DelazJ** 2019-11-13 10:49 UTC
Labels: 3.12, Automatic new feature
