### ISSUE TITLE
Merge pull request #3907 from alexbruy/remove-gdaltools

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1598] opened 2016-12-27 17:18 UTC
Original commit: https://github.com/qgis/QGIS/commit/110ffe2756c0e8871218c3ef350d3b59c5df00a4 by web-flow

[FEATURE] replace GDALTools plugin with Processing

**Comment by DelazJ** [comment] 2016-12-27 17:34
duplicate of #1597

**Closed by DelazJ** 2016-12-27 17:34 UTC
Labels: Automatic new feature
