### ISSUE TITLE
[layouts][needs-docs] Add missing tool actions to Edit menu

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2460] opened 2018-03-21 23:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/8a5924d0f10a7749667ccb93b2887c0186d17751 by nyalldawson

Fixes #18494

**Comment by DelazJ** [comment] 2018-03-22 05:09
Duplicate of #2461

**Closed by DelazJ** 2018-03-22 05:09 UTC
Labels: Automatic new feature
