### ISSUE TITLE
Merge pull request #7889 from borysiasty/plugins_from_encrypted_zips

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3009] opened 2018-09-14 10:05 UTC
Original commit: https://github.com/qgis/QGIS/commit/ec2ddb4295badd6953237e5e9182b7903f429e5a by web-flow

[FEATURE][Plugin installer] Support for encrypted zips when installing plugins from local files

**Comment by DelazJ** [comment] 2018-09-14 10:17
Duplicate of #3008

**Closed by DelazJ** 2018-09-14 10:17 UTC
Labels: Automatic new feature
