### ISSUE TITLE
Merge pull request #8509 from wonder-sk/terrain-map-themes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3187] opened 2018-11-22 08:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/d4ef55dadb6c850b9ee38d343b3eda3612a8077f by web-flow

[FEATURE] Optionally use a map theme to render terrain textures

**Comment by DelazJ** [comment] 2018-11-22 08:50
Duplicate of #3186

**Closed by DelazJ** 2018-11-22 08:50 UTC
Labels: Automatic new feature
