### ISSUE TITLE
[FEATURE][processing] New algorithm for merging connected lines

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1231] opened 2016-08-02 04:45 UTC
Original commit: https://github.com/qgis/QGIS/commit/30fcaed634aa43d01528a031fd8f2d255f97f837 by nyalldawson

This algorithm joins all connected parts of MultiLineString
geometries into single LineString geometries.

If any parts of the input MultiLineString geometries are not
connected, the resultant geometry will be a MultiLineString
containing any lines which could be merged and any non-connected
line parts.

**Comment by DelazJ** [comment] 2016-08-10 12:10
duplicate of #1274

**Closed by DelazJ** 2016-08-10 12:10 UTC
Labels: Automatic new feature
