### ISSUE TITLE
[FEATURE] Identification map tool for 3D views

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2984] opened 2018-09-10 15:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/c5d88436a8a51c80e0b238e0e3d260dfb72adb07 by wonder-sk

Currently identification only works on terrain and does not highlight in 3D

**Comment by havatv** [comment] 2018-12-31 02:44
Seems to be a duplicate of #2979.

**Closed by havatv** 2018-12-31 02:44 UTC
Labels: Automatic new feature
