### ISSUE TITLE
Merge pull request #3685 from nirvn/array_unique

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1480] opened 2016-10-28 04:11 UTC
Original commit: https://github.com/qgis/QGIS/commit/8be3b01b12c12fd915162ebb308a8efaa3c0aa06 by web-flow

[FEATURE] add array_distinct() function

**Comment by DelazJ** [comment] 2016-10-28 08:11
duplicate of #1479

**Closed by DelazJ** 2016-10-28 08:11 UTC
Labels: Automatic new feature
