### ISSUE TITLE
[MESH] Resampling from vertex values to face values (#35264)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5126] opened 2020-03-24 09:03 UTC
Original commit: https://github.com/qgis/QGIS/commit/34d44c08ed3863447ec9a954d9a9c738a1f17aee by web-flow

[FEATURE] Implements resampling from values on vertices to values on faces with the neighbor average method. (note that resampling method for datasets defined on faces, e.g., the value on vertices is calculated from value on faces was added in the previous QGIS release)

The default method is set to "none" for resampling from vertices to faces and to "neighbor average" for resampling from faces to vertices. Then the default rendering is now always smooth.

**Comment by DelazJ** [comment] 2020-03-24 09:14
Duplicate of #5127

**Closed by DelazJ** 2020-03-24 09:14 UTC
Labels: 3.14, Automatic new feature
