### ISSUE TITLE
Training Manual Vector Analysis module (buildings layer)

### ISSUE THREAD

**Issue by stutzmat** [qgis/QGIS-Documentation#6180] opened 2020-10-08 21:23 UTC
## Description
I repeatedly receive the following error when completing the training manual exercise 6.2.9. (Vector Analysis module)  The Extract by Location processing tool does not execute with the buildings layer, but there was no problem when I substituted another layer.  The error reads as follows: 
_**Feature (1) has invalid geometry. Please fix the geometry or change the Processing setting to the "Ignore invalid input features" option.
Execution failed after 0.12 seconds_**

Page URL:

**Comment by DiGro** [comment] 2020-11-27 17:36
Did check the training manual and then searched for the cause of this report.
Training manual says to use the layer buildings_34S, which is the buildings.shp from the training dataset, converted to EPSG 32734 : WGS 84 / UTM zone 34S. (Exercise 6.2.5)

Exercise 6.2.9 says to use layer buildings_34S, NOT buildings.shp

Layer buildings_34S does NOT provide the reported error
Layer buildings.shp, from the dataset, DOES produce the error

Since Training manual says to use buildings_34S, and NOT buildings.shp, the manual is correct en does deliver the required result.
[https://docs.qgis.org/3.10/nl/docs/training_manual/vector_analysis/basic_analysis.html#backlink-vector-analysis-basic-1](url)

Therefore this PR can/should be closed

**Comment by DelazJ** [comment] 2020-11-28 17:13
Thanks for the test @DiGro 
@stutzmat please test with the right file. Thanks.
I'm closing then.

**Closed by DelazJ** 2020-11-28 17:13 UTC
Labels: Training Manual
