### ISSUE TITLE
[FEATURE]: possibility to segmentize feature info geometry in server

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1351] opened 2016-08-25 15:39 UTC
Original commit: https://github.com/qgis/QGIS/commit/24cc0e2febe76de1a11bb3db7edc24d3cbcac38f by mhugent

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-30 11:07
duplicate of #1353

**Closed by DelazJ** 2016-08-30 11:07 UTC
Labels: Automatic new feature
