### ISSUE TITLE
[FEATURE] enable auto completion in locator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6091] opened 2020-09-09 12:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/002a7033f09f714ef2671d0e778e5418ab513539 by 3nids

a locator filter can now return a completion list while preparing the search
the line edit will use the first matching completion and display it as light grey text
the completion can be triggered by pressing Tab key

**Comment by DelazJ** [comment] 2020-09-09 12:03
Duplicate of #6094

**Closed by DelazJ** 2020-09-09 12:03 UTC
Labels: 3.14, Automatic new feature
