### ISSUE TITLE
Merge pull request #4299 from alexbruy/checkable-combobox

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1816] opened 2017-04-10 06:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/78d02b7fabfb19f7862d98fc7a1981875e626cca by web-flow

[FEATURE] New custom widget checkable combobox

**Comment by DelazJ** [comment] 2017-04-10 08:13
duplicate of #1815

**Closed by DelazJ** 2017-04-10 08:13 UTC
Labels: Automatic new feature
