### ISSUE TITLE
[API][FEATURE] Allow setting a custom path pre-processor for QgsPathResolver

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4021] opened 2019-07-24 22:41 UTC
Original commit: https://github.com/qgis/QGIS/commit/2237c6ae9967eaaaaf4a18fa58c4e9c6d6f4fe01 by nyalldawson

QgsPathResolver::setPathPreprocessor allows setting a custom path pre-processor
function, which allows for manipulation of paths and data sources prior
to resolving them to file references or layer sources.

The processor function must accept a single string argument (representing the
original file path or data source), and return a processed version of this path.

The path pre-processor function is called before any bad layer handler.

Example - replace an outdated folder path with a new one:

  def my_processor(path):
    return path.replace('c:/Users/ClintBarton/Documents/Projects', 'x:/Projects/')

  QgsPathResolver.setPathPreprocessor(my_processor)

Example - replace a stored database host with a new one:

  def my_processor(path):
    return path.replace('host=10.1.1.115', 'host=10.1.1.116')

  QgsPathResolver.setPathPreprocessor(my_processor)

Example - replace stored database credentials with new ones:

  def my_processor(path):
    path= path.replace("user='gis_team'", "user='team_awesome'")
    path = path.replace("password='cats'", "password='g7as!m*'")
    return path

  QgsPathResolver.setPathPreprocessor(my_processor)

**Comment by SrNetoChan** [comment] 2019-07-30 12:21
Duplicate of #4027

**Closed by SrNetoChan** 2019-07-30 12:21 UTC
Labels: Automatic new feature
