### ISSUE TITLE
[FEATURE][3d] Measurement tool #30299

### ISSUE THREAD

**Issue by ismailsunni** [qgis/QGIS-Documentation#4157] opened 2019-08-27 14:34 UTC
## Description
Manually created, the original PR is https://github.com/qgis/QGIS/pull/30299 and the commit : https://github.com/qgis/QGIS/commit/edd921c428dc70f955379385ced85002dca1054c

Page URL:

**Comment by DelazJ** [comment] 2020-04-03 16:28
Duplicate of #3970

**Closed by DelazJ** 2020-04-03 16:28 UTC
