### ISSUE TITLE
Merge pull request #6865 from PeterPetrik/qgsquick_1_canvas_merge

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2620] opened 2018-05-09 05:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/29489e1056ed9e7ff0d17d22b75d2711e4b2acec by web-flow

[FEATURE] Introduction of QGIS Quick library

**Comment by DelazJ** [comment] 2018-05-09 07:31
Duplicate of #2619

**Closed by DelazJ** 2018-05-09 07:31 UTC
Labels: Automatic new feature
