### ISSUE TITLE
Merge pull request #4111 from nyalldawson/refresh_layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1684] opened 2017-02-13 19:48 UTC
Original commit: https://github.com/qgis/QGIS/commit/f2ac60ab54c6a502d85850288c53c62be9179266 by web-flow

[FEATURE] Allow layers to be automatically refreshed at a specified interval

**Comment by DelazJ** [comment] 2017-02-14 08:40
duplicate of #1683

**Closed by DelazJ** 2017-02-14 08:40 UTC
Labels: Automatic new feature
