### ISSUE TITLE
[FEATURE] Holding shift while using map zoom tools inverts the zoom

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1646] opened 2017-01-24 04:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/5e1339e863312bbf457303907c919eaf008d9f0e by web-flow

[FEATURE] Holding shift while using map zoom tools inverts the zoom

**Comment by DelazJ** [comment] 2017-04-03 11:34
duplicate of #1644

**Closed by DelazJ** 2017-04-03 11:34 UTC
Labels: Automatic new feature
