### ISSUE TITLE
Merge pull request #4881 from boundlessgeo/xyz-auth-gui

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1999] opened 2017-07-21 19:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/89ffecbf05f23d4f1f52b9344ebddd6f45dc8599 by web-flow

[feature][needs-docs] XYZ authentication and referer added to GUI

**Comment by DelazJ** [comment] 2017-08-06 21:36
Duplicate of #1998

**Closed by DelazJ** 2017-08-06 21:36 UTC
Labels: Automatic new feature
