### ISSUE TITLE
Merge pull request #3871 from rouault/auto_stretch

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1584] opened 2016-12-16 12:53 UTC
Original commit: https://github.com/qgis/QGIS/commit/792873af5cb854cf1315f20ec196d8975558e091 by web-flow

[FEATURE] Implement raster auto-stretching when updating canvas

**Comment by DelazJ** [comment] 2016-12-16 13:14
duplicate of #1583

**Closed by DelazJ** 2016-12-16 13:14 UTC
Labels: Automatic new feature
