### ISSUE TITLE
[FEATURE] Preview of WMTS layers + add XYZ tile layers (PR #3473)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1398] opened 2016-09-13 15:37 UTC
Original commit: https://github.com/qgis/QGIS/commit/717e7162f355c3651bcee51535cfb4a6c10781d4 by web-flow

This introduces live preview when rendering WMTS layers - as soon as individual tiles are loaded, they are shown in map canvas... no need to wait with a blank map until all tiles are fully downloaded. Additionally, if there are already locally cached tiles of other zoom levels, they may be used in the preview while the tiles with best matching zoom level are being downloaded. This greatly improves the user experience when working with WMTS layers.

Additionally, I have added native support for XYZ tile layers into WMS provider (based on existing implementation of WMTS tiling). This allows loading of various new raster tile sources (e.g. OpenStreetMap tiles) that were before available only with QuickMapServices or OpenLayers plugins. To use XYZ tile layers, open the browser dock in QGIS and look for "Tile Servers (XYZ)" root entry. Right-clicking will open a menu to add connections. For example for OpenStreetMap the URL would be http://c.tile.openstreetmap.org/{z}/{x}/{y}.png

The work on WMTS live preview has been funded by Land Information New Zealand.

The work on XYZ tile layers has been funded by Lutra Consulting.

**Comment by DelazJ** [comment] 2016-09-16 07:31
duplicate of #1408

**Closed by DelazJ** 2016-09-16 07:31 UTC
Labels: Automatic new feature
