### ISSUE TITLE
[FEATURE][layouts] Allow scalebar line style to be set using
standard QGIS line symbols

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5088] opened 2020-03-22 06:41 UTC
Original commit: https://github.com/qgis/QGIS/commit/9378dcd73f125b738d5c2a66a3f11b6c213f77c9 by nyalldawson

Instead of the previous settings of scalebar line color/width/cap styles,
we now expose the option as a full line symbol for more advanced styling

Also some code cleanups

Sponsored by SLYR

**Comment by DelazJ** [comment] 2020-03-23 16:30
Duplicate of #5090

**Closed by DelazJ** 2020-03-23 16:30 UTC
Labels: 3.14, Automatic new feature
