### ISSUE TITLE
[needs-docs][processing] Add option to check validity alg to ignore self-intersection
causing rings errors

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3475] opened 2019-02-26 20:05 UTC
Original commit: https://github.com/qgis/QGIS/commit/49742c302afb97e6272ce8b6b3a806014cdbdb5b by nyalldawson

By default the algorithm now uses the strict OGC definition of polygon validity, where
a polygon is marked as invalid if a self-intersecting ring causes an interior hole.
If the "Ignore ring self intersections" option is checked, then this rule will be
ignored and a more lenient validity check will be performed.

Refs #16418, refs #21336

**Comment by DelazJ** [comment] 2019-03-05 12:31
Duplicate of #3485

**Closed by DelazJ** 2019-03-05 12:31 UTC
Labels: Automatic new feature
