### ISSUE TITLE
Merge pull request #6982 from elpaso/currentformfeature-expressions-4

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2638] opened 2018-05-16 07:48 UTC
Original commit: https://github.com/qgis/QGIS/commit/a44eeae44130e30f7117431d4a62c37320af9536 by web-flow

[feature][need-docs] Current feature/current value form context expressions

**Comment by DelazJ** [comment] 2018-05-16 08:45
Duplicate of #2637

**Closed by DelazJ** 2018-05-16 08:45 UTC
Labels: Automatic new feature
