### ISSUE TITLE
Merge pull request #7393 from ghtmtt/processing_sampling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2791] opened 2018-07-16 08:49 UTC
Original commit: https://github.com/qgis/QGIS/commit/0c62abed969c8bd37168e26823483a0439a8771d by web-flow

[processing][FEATURE] Sample raster values to point

**Comment by DelazJ** [comment] 2018-07-16 09:03
Duplicate of #2790

**Closed by DelazJ** 2018-07-16 09:03 UTC
Labels: Automatic new feature
