### ISSUE TITLE
[FEATURE] control over drawing of composer table grid horizontal & vertical lines

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1449] opened 2016-10-14 06:42 UTC
Original commit: https://github.com/qgis/QGIS/commit/ec2d7fea0c651545df4cc936a2808817f0dc705a by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-10-14 07:31
duplicate of #1450

**Closed by DelazJ** 2016-10-14 07:31 UTC
Labels: Automatic new feature
