### ISSUE TITLE
Merge pull request #3755 from nirvn/style_manager_upgrade

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1527] opened 2016-11-17 02:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/e624518e0062c18ddffba51ec364ebd1d85db703 by web-flow

[FEATURE] Style management re-work and upgrade

**Comment by DelazJ** [comment] 2016-11-17 05:24
duplicate of #1526

**Closed by DelazJ** 2016-11-17 05:24 UTC
Labels: Automatic new feature
