### ISSUE TITLE
Merge pull request #7245 from rouault/gpkg_transactions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2722] opened 2018-06-22 12:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/638fc0ceff2534b2d6f20f136cdb7a72c64e7960 by web-flow

[OGR provider] [FEATURE] Add support for transactions on GPKG databases

**Comment by DelazJ** [comment] 2018-06-22 12:44
duplicate of #2721

**Closed by DelazJ** 2018-06-22 12:44 UTC
Labels: Automatic new feature
