### ISSUE TITLE
[FEATURE][API] Add parts iterators to QgsGeometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3175] opened 2018-11-19 18:05 UTC
Original commit: https://github.com/qgis/QGIS/commit/a22422c4bf55dc1a29483bbb32577d4b554564f4 by nyalldawson

This allows easy iteration over all the parts of a geometry,
regardless of the geometry's type. E.g.

geometry = QgsGeometry.fromWkt( 'MultiPoint( 0 0, 1 1, 2 2)' )
for part in geometry.parts():
  print(part.asWkt())

geometry = QgsGeometry.fromWkt( 'LineString( 0 0, 10 10 )' )
for part in geometry.parts():
  print(part.asWkt())

There are two iterators available. QgsGeometry.parts() gives
a non-const iterator, allowing the parts to be modified in place:

geometry = QgsGeometry.fromWkt( 'MultiPoint( 0 0, 1 1, 2 2)' )
for part in geometry.parts():
   part.transform(ct)

For a const iteration, calling .const_parts() gives a const
iterator, which cannot edit the parts but avoids a potentially expensive
QgsGeometry detach and clone

geometry = QgsGeometry.fromWkt( 'MultiPoint( 0 0, 1 1, 2 2)' )
for part in geometry.const_parts():
   print(part.x())

**Comment by DelazJ** [comment] 2018-11-29 20:10
Duplicate of #3204

**Closed by DelazJ** 2018-11-29 20:10 UTC
Labels: Automatic new feature, PyQGIS Cookbook, ToDocOrNotToDoc?
