### ISSUE TITLE
Merge pull request #36200 from olivierdalang/self_snap

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5561] opened 2020-05-26 12:54 UTC
Original commit: https://github.com/qgis/QGIS/commit/38673f5a7ff5a05a082d61e4b2f7fb2249444c78 by web-flow

[feature] Snapping also snaps to the currently digitised feature

**Comment by DelazJ** [comment] 2020-05-26 13:45
Duplicate of #5560

**Closed by DelazJ** 2020-05-26 13:45 UTC
Labels: 3.14, Automatic new feature
