### ISSUE TITLE
Merge pull request #7835 from m-kuhn/expressionCodeCompletion

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2982] opened 2018-09-10 11:42 UTC
Original commit: https://github.com/qgis/QGIS/commit/41184bf9616c7ac6c4ecff1612c0d13d4e233c7a by web-flow

Code completion for expression builder [FEATURE]

**Comment by DelazJ** [comment] 2018-09-10 15:15
Duplicate of #2981

**Closed by DelazJ** 2018-09-10 15:15 UTC
Labels: Automatic new feature
