### ISSUE TITLE
Merge pull request #3810 from nirvn/colorrampbutton

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1551] opened 2016-11-30 04:27 UTC
Original commit: https://github.com/qgis/QGIS/commit/9bb9b58e124fb874c029dd81c3d3de1b70706205 by web-flow

[FEATURE] color ramp button widget

**Comment by DelazJ** [comment] 2016-11-30 09:23
duplicate of #1550

**Closed by DelazJ** 2016-11-30 09:23 UTC
Labels: Automatic new feature
