### ISSUE TITLE
Close vertex for line when editing. fixes #32359 [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4876] opened 2020-02-04 19:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/6fe51c42070bdf2c900435a0c7ab637e3bb8a5e4 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-02-12 04:46
Duplicate of #4879

**Closed by DelazJ** 2020-02-12 04:46 UTC
Labels: 3.12, Automatic new feature
