### ISSUE TITLE
Merge pull request #3848 from nyalldawson/orthag

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1569] opened 2016-12-09 00:09 UTC
Original commit: https://github.com/qgis/QGIS/commit/5aa1539418d88d6979888c50e43846f46276d2ed by web-flow

[FEATURE][processing] New algorithm to orthagonalize geometries

**Comment by DelazJ** [comment] 2016-12-09 09:42
duplicate of #1568

**Closed by DelazJ** 2016-12-09 09:42 UTC
Labels: Automatic new feature
