### ISSUE TITLE
Missing docs for "Save vector features to file" processing algorithm

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS-Documentation#6820] opened 2021-07-19 17:44 UTC
## Description

Missing docs for "Save vector features to file" (native:savefeatures) algorithm added to the "Vector general" processing group with PR https://github.com/qgis/QGIS/pull/37894

Page URL:
https://docs.qgis.org/testing/en/docs/user_manual/processing_algs/qgis/vectorgeneral.html

**Comment by DelazJ** [comment] 2021-08-12 13:12
Duplicate of #5892

**Closed by DelazJ** 2021-08-12 13:12 UTC
Labels: Processing Alg
