### ISSUE TITLE
Merge pull request #3829 from nirvn/colorrampbutton_save

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1557] opened 2016-12-03 06:41 UTC
Original commit: https://github.com/qgis/QGIS/commit/a26434e8bdacdb5d822a44816b7b22b0539d6149 by web-flow

- [FEATURE] save existing color ramp function
- improve new color ramp type naming

**Comment by DelazJ** [comment] 2016-12-09 09:58
duplicate of #1556

**Closed by DelazJ** 2016-12-09 09:58 UTC
Labels: Automatic new feature
