### ISSUE TITLE
[needs-docs] Harmonize display of GDAL build vrt options

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3751] opened 2019-05-19 22:52 UTC
Original commit: https://github.com/qgis/QGIS/commit/bd2fc75f2e05a735eab4b0ac140f8628dc606139 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2019-05-22 06:14
Duplicate of #3763

**Closed by DelazJ** 2019-05-22 06:14 UTC
Labels: Automatic new feature
