### ISSUE TITLE
Merge pull request #3304 from nyalldawson/processing_clip

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1242] opened 2016-08-03 04:59 UTC
Original commit: https://github.com/qgis/QGIS/commit/c695571c55179834f882cded5326d84c8f660324 by web-flow

[FEATURE] Optimise processing clip algorithm

**Comment by DelazJ** [comment] 2016-08-10 11:42
duplicate of #1276

**Closed by DelazJ** 2016-08-10 11:42 UTC
Labels: Automatic new feature
