### ISSUE TITLE
[FEATURE] Expression function for calculating geometry boundary

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1213] opened 2016-07-28 00:12 UTC
Original commit: https://github.com/qgis/QGIS/commit/1a4ceb1680e9adb4dd78c1bc11887c5a05ba0d19 by nyalldawson

The new 'boundary(...)' function returns a geometry's topological
boundary, ie for polygons this is a multilinestring representing
the polygons rings

**Comment by DelazJ** [comment] 2016-08-10 12:08
duplicate of #1272

**Closed by DelazJ** 2016-08-10 12:08 UTC
Labels: Automatic new feature
