### ISSUE TITLE
[FEATURE] DWG import into geopackage using libdxfrw

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1580] opened 2016-12-14 21:18 UTC
Original commit: https://github.com/qgis/QGIS/commit/a85fe1fa4464e5b6f7bd7e9dbb76c679ec75ec29 by jef-n

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-12-14 22:38
duplicate of #1579

**Closed by DelazJ** 2016-12-14 22:38 UTC
Labels: Automatic new feature

**Comment by jef-n** [comment] 2016-12-17 19:24
The functionality is available in the file menu just below DXF export.  In the dialog you have to input a location for a GeoPackage file, that will be created to import the DWG content to.  You also need to specify which coordinate system the data in the DWG data is in.   The "import" button then allows to import a DWG into it (one per geopackage).

There is also the option to "expand block references", which will copy the transformed contents of the corresponding block for each block reference.

After the DWG is imported into the GeoPackage database the list in the lower half of the dialog is populated with the layer list from the DWG.  There you can selected which layers to import into the QGIS project.  For the DWG a toplevel group with the given name from dialog is created and inside another group for each of selected layers in the list. Alternatively using the option "Merge layers" all layers in one group. Each subgroup contains vector layers for the point, line, label and area features of the respective layer.  The style of each layer is setup so that it resembles the look it originally had in *CAD.
