### ISSUE TITLE
Merge pull request #7892 from PeterPetrik/identify_by_feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3017] opened 2018-09-14 12:15 UTC
Original commit: https://github.com/qgis/QGIS/commit/1192b635d263955f1547587e697824d907a81fb2 by web-flow

[feature] Identify/Select polygon from existing feature geometry (#19064)

**Comment by DelazJ** [comment] 2018-09-14 12:16
Duplicate of #3016

**Closed by DelazJ** 2018-09-14 12:16 UTC
Labels: Automatic new feature
