### ISSUE TITLE
Merge pull request #3475 from m-kuhn/visibilityTab218

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1400] opened 2016-09-13 19:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/ddc76e29c93e81c30153227de9fe2f937f944fad by web-flow

[Feature] conditional visibility for tabs and groupboxes (backport)

**Comment by DelazJ** [comment] 2016-09-14 08:33
duplicate of #1399

**Closed by DelazJ** 2016-09-14 08:33 UTC
Labels: Automatic new feature
