### ISSUE TITLE
Merge pull request #8519 from elpaso/browser-gpkg-vector-rename

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3184] opened 2018-11-21 15:29 UTC
Original commit: https://github.com/qgis/QGIS/commit/fee3935887f3e04291b0139b7c74a3c2fb11e44e by web-flow

[feature][needs-docs] Allow gpkg vector rename from browser

**Comment by DelazJ** [comment] 2018-11-21 22:33
Duplicate of #3183

**Closed by DelazJ** 2018-11-21 22:33 UTC
Labels: Automatic new feature
