### ISSUE TITLE
Merge pull request #3427 from nyalldawson/inline_map_unit

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1347] opened 2016-08-23 23:37 UTC
Original commit: https://github.com/qgis/QGIS/commit/5d38dcbaff1372c27d17469b937d7dea9896575e by web-flow

[FEATURE] Make map unit scaling dialog show inline in style dock

**Comment by DelazJ** [comment] 2016-08-24 09:31
duplicate of #1346

**Closed by DelazJ** 2016-08-24 09:31 UTC
Labels: Automatic new feature
