### ISSUE TITLE
[FEATURE] Mouse wheel over sliders in color dialog to change value by
increments

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1181] opened 2016-07-11 00:28 UTC
Original commit: https://github.com/qgis/QGIS/commit/d3582abbf68e760a10f5785f29be6a1d43967380 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-10 12:14
duplicate of #1204

**Closed by DelazJ** 2016-08-10 12:14 UTC
Labels: Automatic new feature, User Manual
