### ISSUE TITLE
Merge pull request #2964 from nirvn/simple_marker_join_style

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#948] opened 2016-04-03 06:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/ae9d089142b3d348d200c9f7f7f960c5bc180b56 by nyalldawson

[FEATURE] add outline join style settings to simple markers (fixes #3797)

**Comment by DelazJ** [comment] 2016-04-03 07:38
This is a duplicate of #947. Can it be a bug in the automatic script that generates double insertion?
@rduivenvoorde @nyalldawson

**Comment by yjacolin** [comment] 2016-04-04 07:21
Two different commits will create two different doc issues :)

**Closed by yjacolin** 2016-04-04 07:21 UTC
Labels: Automatic new feature
