### ISSUE TITLE
[FEATURE][MESH] plug mesh layer to QGIS temporal framework (#35466)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5225] opened 2020-04-03 06:21 UTC
Original commit: https://github.com/qgis/QGIS/commit/75ddf3c7a6a7cb77b962dcb84abef9d36dbc2832 by web-flow

[FEATURE] Use temporal controller for the mesh layer time handling.

**Comment by DelazJ** [comment] 2020-04-03 08:32
Duplicate of #5226

**Closed by DelazJ** 2020-04-03 08:32 UTC
Labels: 3.14, Automatic new feature
