### ISSUE TITLE
[FEATURE][labels] allow to delete custom label rotation

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4456] opened 2019-11-20 10:46 UTC
Original commit: https://github.com/qgis/QGIS/commit/0e110cf01a29ebea9cf40f0166e0150f55f471ac by 3nids

by pressing DEL key when moving the label

**Comment by havatv** [comment] 2019-11-20 15:49
Seems to be a duplicate of #4455.

**Comment by DelazJ** [comment] 2019-11-20 16:10
Actually, one is about displacement, the other the rotation

**Comment by havatv** [comment] 2019-11-20 16:16
You are right! Sorry.

**Closed** 2021-05-09 18:41 UTC
Labels: 3.12, Automatic new feature, Labels, User Manual
