### ISSUE TITLE
[FEATURE] Substitution list support for labeling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1362] opened 2016-08-30 03:25 UTC
Original commit: https://github.com/qgis/QGIS/commit/7dea9700a6d63a89480a915934c3c2af8e8edfa4 by nyalldawson

Adds the ability to specify a list of text substitutes to make
which apply to label text. Eg abbrevating street types.

Users can export and import lists of substitutes to make
reuse and sharing easier.

**Comment by DelazJ** [comment] 2016-08-30 11:00
duplicate of #1361

**Closed by DelazJ** 2016-08-30 11:00 UTC
Labels: Automatic new feature
