### ISSUE TITLE
[layouts][needs-docs] Add a PDF export settings dialog which is shown
whenever exporting a layout to PDF

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3238] opened 2018-12-11 02:28 UTC
Original commit: https://github.com/qgis/QGIS/commit/8ea3889368e129b651deb0016144d9f0dad671a8 by nyalldawson

This matches the behavior with SVG and raster exports, and allows users
to set specific properties for the export (such as text rendering format)

Fixes #8844

**Comment by DelazJ** [comment] 2018-12-11 13:35
Duplicate of #3241

**Closed by DelazJ** 2018-12-11 13:35 UTC
Labels: Automatic new feature
