### ISSUE TITLE
[feature] Add flag to only copy selected features

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1402] opened 2016-09-15 09:20 UTC
Original commit: https://github.com/qgis/QGIS/commit/59a3bc2ca73696df7d79c5e593cfbe258901bd50 by m-kuhn

This extends the offline editing possibilities to only work on subset of
large layers

Sponsored by DB Fahrwegdienste GmbH

**Comment by DelazJ** [comment] 2016-09-15 09:21
duplicate of #1401

**Closed by DelazJ** 2016-09-15 09:21 UTC
Labels: Automatic new feature
