### ISSUE TITLE
[FEATURE] Allow custom projections to be defined using WKT strings
instead of just proj strings

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4645] opened 2019-12-18 02:44 UTC
Original commit: https://github.com/qgis/QGIS/commit/59a2cf142430a49c5b9ac2d2c8a3edd34d400167 by nyalldawson

WKT strings are lossless and allow definition of a much wider range
of projections than are possible using proj strings.

A new combo box in the Custom Projections dialog allows users to
choose whether the new projection is defined using a WKT or PROJ string.
If possible, the current projection definition is automatically converted
when the combo box is changed by the user.

Also fixes #25918 in the process

**Comment by DelazJ** [comment] 2019-12-20 09:29
Duplicate of #4655

**Closed by DelazJ** 2019-12-20 09:29 UTC
Labels: 3.12, Automatic new feature
