### ISSUE TITLE
Merge pull request #3379 from nyalldawson/processing

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1286] opened 2016-08-11 08:30 UTC
Original commit: https://github.com/qgis/QGIS/commit/8a31576d3a94b395b849838693b734e25a105fce by web-flow

[FEATURE][processing] New algorithm for offsetting lines

**Comment by DelazJ** [comment] 2016-08-11 08:33
duplicate of #1285

**Closed by DelazJ** 2016-08-11 08:33 UTC
Labels: Automatic new feature
