### ISSUE TITLE
Merge pull request #33794 from alexbruy/rectangles-ovals-diamonds

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4790] opened 2020-01-16 13:07 UTC
Original commit: https://github.com/qgis/QGIS/commit/fe7085de945e9ac4cb0f8f54ab3a15d67c85e78f by web-flow

[processing][needs-docs] port Rectangle,ovals,diamonds algorithm to C++

**Comment by havatv** [comment] 2020-01-16 19:14
Duplicate of #4789.

**Closed by havatv** 2020-01-16 19:14 UTC
Labels: 3.12, Automatic new feature
