### ISSUE TITLE
[feature][processing] Complete random raster algorithm collection #2

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5391] opened 2020-05-03 20:28 UTC
Original commit: https://github.com/qgis/QGIS/commit/096b80e44462760728b7cb93d86132d312ebe2ed by web-flow

This refactors and completes the recently added work on random number raster layer creation algorithms (see #35835) and reworks the single algorithm implementation proposed in #36065 to a base-algorithm solution which avoids duplicate code.

With the new algorithms aimed towards distribution based random number creation, QGIS reaches to the same level of functionality as current ArcGIS random raster creation tools. In total, the PR adds the following algorithms (normal and uniform raster layer creation algs are refactored to be in line the new naming scheme):

Create random raster layer (binomial distribution)
Create random raster layer (exponential distribution)
Create random raster layer (gamma distribution)
Create random raster layer (negative binomial distribution)
Create random raster layer (normal distribution)
Create random raster layer (poisson distribution)
Create random raster layer (uniform distribution)

**Comment by DelazJ** [comment] 2020-05-07 10:02
Duplicate of #5394

**Closed by DelazJ** 2020-05-07 10:02 UTC
Labels: 3.14, Automatic new feature
