### ISSUE TITLE
Merge pull request #4732 from nyalldawson/alg

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1955] opened 2017-06-20 03:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/349f6eae6ee3dfd760f2b3bbb850706095151423 by web-flow

[FEATURE] Subdivide algorithm for geometries

**Comment by DelazJ** [comment] 2017-06-20 07:13
Duplicate of #1953

**Closed by DelazJ** 2017-06-20 07:13 UTC
Labels: Automatic new feature
