### ISSUE TITLE
Merge pull request #3863 from rldhont/postgres-compile-expression-functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1607] opened 2017-01-02 16:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/f59acade4b833842a64ab70da6deeb5b05bfcabe by web-flow

[Feature][PostgreSQL] Compile expression functions

**Comment by DelazJ** [comment] 2017-01-02 16:26
duplicate of #1605

**Closed by DelazJ** 2017-01-02 16:26 UTC
Labels: Automatic new feature
