### ISSUE TITLE
Merge pull request #4598 from Gustry/atlas_expressions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1924] opened 2017-05-28 23:10 UTC
Original commit: https://github.com/qgis/QGIS/commit/83815baacff1a24403d533d34e974ab60a494552 by web-flow

[needs-docs] add layerid and layername to atlas expressions

**Comment by DelazJ** [comment] 2017-05-29 07:32
duplicate of #1923

**Closed by DelazJ** 2017-05-29 07:32 UTC
Labels: Automatic new feature
