### ISSUE TITLE
Merge pull request #5090 from nyalldawson/raster_layer_extent

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2065] opened 2017-08-30 23:02 UTC
Original commit: https://github.com/qgis/QGIS/commit/9fa12ac57f2adf532a1c52852424c823e848cf0c by web-flow

[FEATURE] New algorithm for creating vector layer from raster layer's extent

**Comment by DelazJ** [comment] 2017-08-31 09:00
duplicate of #2064

**Closed by DelazJ** 2017-08-31 09:00 UTC
Labels: Automatic new feature
