### ISSUE TITLE
Merge pull request #3787 from nyalldawson/spatialite_index

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1561] opened 2016-12-05 00:54 UTC
Original commit: https://github.com/qgis/QGIS/commit/be4c8156c62fcb66b51f4e5def62310d532d60b9 by web-flow

[FEATURE] Create attribute index support for spatialite provider

**Comment by DelazJ** [comment] 2016-12-05 07:10
duplicate of #1560

**Closed by DelazJ** 2016-12-05 07:10 UTC
Labels: Automatic new feature
