### ISSUE TITLE
Merge pull request #3344 from nyalldawson/line_merge

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1220] opened 2016-07-28 19:10 UTC
Original commit: https://github.com/qgis/QGIS/commit/d87f2abf56076ec7d0e9031bf8678bfbcd9dff40 by web-flow

[FEATURE] API + expression function for merging linestrings

**Comment by DelazJ** [comment] 2016-08-10 12:13
duplicate of #1271

**Closed by DelazJ** 2016-08-10 12:13 UTC
Labels: Automatic new feature
