### ISSUE TITLE
Merge pull request #9495 from m-kuhn/default-enable-geometry-checks

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3542] opened 2019-03-14 07:46 UTC
Original commit: https://github.com/qgis/QGIS/commit/ab530e4b04865201a2ce921f4edbeb477bbc7b01 by web-flow

Make default geometry checks configurable via settings [needs-docs]

**Comment by DelazJ** [comment] 2019-03-14 08:40
Duplicate of #3541

**Closed by DelazJ** 2019-03-14 08:40 UTC
Labels: Automatic new feature
