### ISSUE TITLE
Merge pull request #3678 from nirvn/string_to_array_to_string

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1477] opened 2016-10-27 18:44 UTC
Original commit: https://github.com/qgis/QGIS/commit/fb4578131fe95764f25288bebfaf326ad7bb7fe3 by web-flow

[FEATURE] add string_to_array() and array_to_string() functions

**Comment by DelazJ** [comment] 2016-10-27 19:06
duplicate of #1476

**Closed by DelazJ** 2016-10-27 19:06 UTC
Labels: Automatic new feature
