### ISSUE TITLE
New parameter for WMS service: tile_buffer [needs-docs][FEATURE]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4031] opened 2019-07-25 13:51 UTC
Original commit: https://github.com/qgis/QGIS/commit/789d2c98845a3e34d88db7d15b4e919201c88831 by mbernasocchi

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2019-07-31 07:17
Duplicate of #3908

**Closed** 2019-07-31 07:17 UTC
Labels: Automatic new feature
