### ISSUE TITLE
[feature][processing] Add Line denisty algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4762] opened 2020-01-10 00:32 UTC
Original commit: https://github.com/qgis/QGIS/commit/ce342f7ac4ebec772c5e8142e1549634de34ed5f by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment] 2020-01-10 09:46
Duplicate of #4763.

**Closed by havatv** 2020-01-10 09:46 UTC
Labels: 3.12, Automatic new feature, Processing Alg
