### ISSUE TITLE
[FEATURE] Make links in feature identify results clickable

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1197] opened 2016-07-13 21:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/0075a4bb1664463aac67e92f5558ad804af0156c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-10 11:51
duplicate of #1203

**Closed by DelazJ** 2016-08-10 11:51 UTC
Labels: Automatic new feature
