### ISSUE TITLE
OGR: add a download option to the protocol data source [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3437] opened 2019-02-06 22:08 UTC
Original commit: https://github.com/qgis/QGIS/commit/0557c70034c6b603ab7e8c6c0f4881587fe0e84b by nyalldawson

OGR: add a download option to the protocol data source [needs-docs]

Cherry-picked from master 1f8708f270

**Comment by DelazJ** [comment] 2019-02-07 05:46
Duplicate of #3404

**Closed by DelazJ** 2019-02-07 05:46 UTC
Labels: Automatic new feature
