### ISSUE TITLE
Merge pull request #31374 from troopa81/parallelize_snap_caching

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4219] opened 2019-09-06 11:29 UTC
Original commit: https://github.com/qgis/QGIS/commit/87b1aa9a5d6efb279693aea68dc2dcb5b51b3e86 by web-flow

[FEATURE] Parallelize snap index build

**Comment by DelazJ** [comment] 2019-09-06 12:18
duplicate of #4218

**Closed by DelazJ** 2019-09-06 12:18 UTC
Labels: Automatic new feature
