### ISSUE TITLE
[FEATURE][processing] Export layout atlas as PDF algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6006] opened 2020-08-11 02:07 UTC
Original commit: https://github.com/qgis/QGIS/commit/13be3de4139a0caa667ebdfdc536a89ce744789d by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-08-11 08:06
Duplicate of #6007

**Closed by DelazJ** 2020-08-11 08:06 UTC
Labels: 3.14, Automatic new feature
