### ISSUE TITLE
Merge pull request #4110 from nyalldawson/label_cache

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1673] opened 2017-02-07 04:29 UTC
Original commit: https://github.com/qgis/QGIS/commit/0f5b3fd1296f2a6a5af309e2a50e9ffb93aafb71 by web-flow

[FEATURE] Cache labeling result to avoid unnecessary redraws when refreshing canvas

**Comment by DelazJ** [comment] 2017-02-07 06:39
Duplicate of #1672

**Closed by DelazJ** 2017-02-07 06:39 UTC
Labels: Automatic new feature
