### ISSUE TITLE
Merge pull request #3438 from nyalldawson/replace

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1360] opened 2016-08-29 22:46 UTC
Original commit: https://github.com/qgis/QGIS/commit/891370fd689994b6566abf46fe4b50a1a91b6290 by web-flow

[FEATURE] Substitution list support for labeling

**Comment by DelazJ** [comment] 2016-08-30 11:02
duplicate of #1361

**Closed by DelazJ** 2016-08-30 11:02 UTC
Labels: Automatic new feature
