### ISSUE TITLE
[processing][needs-docs] Adjust status of controls in algorithm dialog

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5048] opened 2020-03-18 13:42 UTC
Original commit: https://github.com/qgis/QGIS/commit/237f1f7e2dc7372071254ebf2ac267e140e2e6da by gacarrillor

  + Run button is not shown anymore in the Log tab, therefore, you can only run algorithms from the Parameters tab.
  + While running an algorithm, the Parameters tab is now blocked.
  + When an algorithm execution finishes (either successfully or not), a new button Change Parameters is shown in the Log tab.
  + The Batch Algorithm Dialog is now consistent with the described behavior (before, it blocked the Parameters panel, but not the tab; and it was the only dialog blocking parameters widgets).

These changes were applied to the Algorithm Dialog and Batch Algorithm Dialog, and work on Edit in place dialogs as well.

**Comment by havatv** [comment] 2020-03-18 19:05
Something needs to be done in the "Algorithm dialog" section (22.3.1)? At least update the screenshot with the log panel (Fig. 22.16: Algorithm Dialog - Log) and check the text.

**Comment by careyshan** [comment] 2021-11-01 10:59
Hi @DelazJ , 
Is this one closed now? From looking at the docs, it still needs updating - I can do it today if needs be.

Cheers

**Comment by DelazJ** [comment] 2021-11-01 12:04
Not closed, needs update. The `closed` mention above refers to a duplicate issue report.

**Comment by DelazJ** [comment] 2021-11-02 08:14
@careyshan I discovered that this report duplicates #5113 which provides more info and is generated from the code pull request itself. I suggest we close this one.

**Comment by careyshan** [comment] 2021-11-02 15:49
@DelazJ - ok so close this one and fix #5113?

Cheers

**Comment by DelazJ** [comment] 2021-11-04 07:23
Duplicate of #5113

**Closed by DelazJ** 2021-11-04 07:23 UTC
Labels: Text, Showcase/Screenshots, User Manual, Automatic new feature, Easy fix, Processing, 3.14
