### ISSUE TITLE
[needs-docs][FEATURE] Add reverse line maptools AKA swap direction

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2957] opened 2018-09-04 22:59 UTC
Original commit: https://github.com/qgis/QGIS/commit/e10d16e1da3c94fac7e6a7fbe244780fa47a0e57 by web-flow

[needs-docs][FEATURE] Add reverse line maptools AKA swap direction

**Comment by lajunek** [comment] 2019-12-05 10:18
@DelazJ @SrNetoChan I can implement this

**Comment by lajunek** [comment] 2019-12-05 10:24
@DelazJ how can I find out if somebody already made a branch for implementing this in the docs?

**Comment by DelazJ** [comment] 2019-12-06 05:52
@lajunek I'm not sure there's a better and faster solution than this one: you mention your interest here, nobody reacts, then I'd assume that nobody is working on it. Don't waste your time on checking others' branches.

**Comment by DelazJ** [comment] 2019-12-07 09:31
Fixed in #4570

**Comment by lajunek** [comment] 2019-12-07 09:51
@DelazJ how should the issue be closed? You told me we shouldn't close the issues manually and only by the PRs that deal with the issue.

**Comment by DelazJ** [comment] 2019-12-07 11:28
If you add `fix #issue` (the "fix" is mandatory) in the first comment of PR, it will close automatically. See https://docs.qgis.org/testing/en/docs/documentation_guidelines/first_contribution.html#describe-your-pull-request In your PR, the issue is simply referenced.

**Closed** 2019-12-07 13:47 UTC
Labels: 3.4, Automatic new feature, Screenshots, Text, User Manual

**Comment by DelazJ** [comment] 2019-12-07 16:01
>@DelazJ how should the issue be closed?

> havatv closed this 2 hours ago

Oups... I forgot to "comment and close"
