### ISSUE TITLE
Merge pull request #3968 from nyalldawson/item_vars

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1618] opened 2017-01-11 03:15 UTC
Original commit: https://github.com/qgis/QGIS/commit/3e2b4fc421ca418ae908e60d39beaa736485f2c2 by web-flow

[FEATURE] item_variables expression function inside compositions

**Comment by DelazJ** [comment] 2017-01-11 04:37
duplicate of #1616

**Closed by DelazJ** 2017-01-11 04:37 UTC
Labels: Automatic new feature
