### ISSUE TITLE
Merge pull request #3935 from rouault/group_visibility

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1612] opened 2017-01-04 14:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/f67cdc3965187cc62002e005aedb6a43956ea282 by web-flow

[FEATURE] Change of ergonomy of the visibility of layers inside groups

**Comment by DelazJ** [comment] 2017-01-04 14:25
duplicate of #1611

**Closed by DelazJ** 2017-01-04 14:25 UTC
Labels: Automatic new feature
