### ISSUE TITLE
Merge pull request #3308 from mhugent/pan_to_feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1199] opened 2016-07-15 07:36 UTC
Original commit: https://github.com/qgis/QGIS/commit/da74b184f2fc031335df50901002d2d25dcff424 by web-flow

[FEATURE]: pan to current feature in attribute table

**Comment by DelazJ** [comment] 2016-07-15 14:04
Right Milestone is 3.0

**Comment by DelazJ** [comment] 2016-08-10 12:05
duplicate of #1198

**Closed by DelazJ** 2016-08-10 12:05 UTC
Labels: Automatic new feature
