### ISSUE TITLE
[FEATURE][processing] New algorithm for geometry boundary

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1278] opened 2016-08-10 09:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/ab022451a58196f2c96f6a0482e2155b5171bad5 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-10 10:12
duplicate of #1281

**Closed by DelazJ** 2016-08-10 10:12 UTC
Labels: Automatic new feature
