### ISSUE TITLE
Merge pull request #3489 from nyalldawson/preset_color_ramp

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1410] opened 2016-09-16 22:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/5e9619249eec6542e5f6a6162c1e11652752edcf by web-flow

[FEATURE] "Preset colors" color ramp

**Comment by DelazJ** [comment] 2016-09-17 09:28
Duplicate of #1409

**Closed by DelazJ** 2016-09-17 09:28 UTC
Labels: Automatic new feature
