### ISSUE TITLE
[needs-docs][postgres] Correctly handle binary (bytea) fields

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3940] opened 2019-07-01 23:14 UTC
Original commit: https://github.com/qgis/QGIS/commit/6e2f94cab746cd97419b2672b4a6f251e515574b by nyalldawson

Previously these would be silently dropped from the layers, but
we now have comprehensive support for binary fields and should
expose them.

Fix sponsored by WhereGroup

**Comment by havatv** [comment] 2019-07-02 07:01
Duplicate of #3928.

**Closed by havatv** 2019-07-02 07:01 UTC
Labels: Automatic new feature
