### ISSUE TITLE
Merge pull request #35875 from olivierdalang/tracing_curves_prototype

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5505] opened 2020-05-15 06:57 UTC
Original commit: https://github.com/qgis/QGIS/commit/0617e52f1994fb9b43227187c66a7280c7380075 by web-flow

[feature] Curved geometries support for trace tool

**Comment by DelazJ** [comment] 2020-05-15 11:59
Duplicate of #5504

**Closed by DelazJ** 2020-05-15 11:59 UTC
Labels: 3.14, Automatic new feature
