### ISSUE TITLE
[feature] Server WFS3 api sorting

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5777] opened 2020-06-28 21:23 UTC
Original commit: https://github.com/qgis/QGIS/commit/02d3eb0814e3bfc2fc3a7f08c5bde1d0b49c95ab by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-06-28 21:57
Duplicate of #5764

**Closed by DelazJ** 2020-06-28 21:57 UTC
Labels: 3.14, Automatic new feature
