### ISSUE TITLE
Merge pull request #7350 from PeterPetrik/quick_featurepanel

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2785] opened 2018-07-13 14:32 UTC
Original commit: https://github.com/qgis/QGIS/commit/12c8f394a51e7cf989281583c5914b89fe68cc1e by web-flow

[quick] [feature] Feature attribute panel

**Comment by DelazJ** [comment] 2018-07-13 22:45
Duplicate of #2784

**Closed by DelazJ** 2018-07-13 22:45 UTC
Labels: Automatic new feature
