### ISSUE TITLE
[Feature] Allow configuring link/unlink feature buttons on relation editor widget

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1416] opened 2016-09-21 19:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/8069154aadd76aa0fd48d4fb3126109728f26963 by m-kuhn

Unfortunately this naughty coder did not write a description... :-(

**Comment by m-kuhn** [comment] 2016-09-21 19:20
In the drag and drop designer, doubleclick a relation item and make use of the two new checkboxes.

**Comment by m-kuhn** [comment] 2016-09-21 19:21
Duplicate of #1415

**Closed by m-kuhn** 2016-09-21 19:21 UTC
Labels: Automatic new feature
