### ISSUE TITLE
Merge pull request #6961 from wonder-sk/union-single-layer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2624] opened 2018-05-10 18:46 UTC
Original commit: https://github.com/qgis/QGIS/commit/b6a26464d4eaa517c4e2afa34f59dbe6bf0e482e by web-flow

[FEATURE] Union algorithm with a single layer

**Comment by DelazJ** [comment] 2018-05-10 19:40
Duplicate of #2623

**Closed by DelazJ** 2018-05-10 19:40 UTC
Labels: Automatic new feature
