### ISSUE TITLE
Merge pull request #4253 from nyalldawson/multi_canvas2

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1765] opened 2017-03-15 00:06 UTC
Original commit: https://github.com/qgis/QGIS/commit/738f4415d925debddc030feffbdfcb0fa91a1bd5 by web-flow

[FEATURE] Multi canvas/additional map views

**Comment by DelazJ** [comment] 2017-03-15 13:17
duplicate of #1764

**Closed by DelazJ** 2017-03-15 13:17 UTC
Labels: Automatic new feature
