### ISSUE TITLE
[FEATURE][callouts] Add control over anchor point for callout on label

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4989] opened 2020-03-09 05:29 UTC
Original commit: https://github.com/qgis/QGIS/commit/bcf9c828f981a2f9f74a39bb06c7401fb670affd by nyalldawson

This gives users control over where a callout should join to the label
text. (Previously, you only had control over where the callout would
join to the corresponding feature geometry).

Choices include:
- Closest point (previous behavior)
- Label Centroid
- Fixed corners: Top left/top right/bottom left/bottom right/etc

Data defined control over the label anchor is also possible

**Comment by DelazJ** [comment] 2020-03-09 09:02
Duplicate of #4990

**Closed** 2020-03-09 09:36 UTC
Labels: 3.14, Automatic new feature
