### ISSUE TITLE
[MESH][FEATURE] update to MDAL 0.5.91 Multi meshes in one file (#35669)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5278] opened 2020-04-14 06:17 UTC
Original commit: https://github.com/qgis/QGIS/commit/17a95ef0a595c6f9334d37e940ac7ea32953b75f by web-flow

Allow load of multiple (sub-)meshes from a single file. If file contains multiple meshes (e.g. UGRID file), user needs to select the meshes to load from the dialog.

**Comment by DelazJ** [comment] 2020-04-14 06:25
Duplicate of #5279

**Closed by DelazJ** 2020-04-14 06:25 UTC
Labels: 3.14, Automatic new feature
