### ISSUE TITLE
Merge pull request #4924 from SrNetoChan/dialog_titles

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2010] opened 2017-07-26 20:27 UTC
Original commit: https://github.com/qgis/QGIS/commit/ce4a2519c1561887617e67618b29e519e161dcce by web-flow

Making dialog titles use Book Style Capitalization [needs-docs]

**Comment by DelazJ** [comment] 2017-08-06 21:32
Duplicate of #2009

**Closed by DelazJ** 2017-08-06 21:32 UTC
Labels: Automatic new feature
