### ISSUE TITLE
[FEATURE][expressions] Add @layers, @layer_ids project scope variables
which contain lists of map layers and map layers ids for all layers
from the current project

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5063] opened 2020-03-20 02:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/7b7c8065b08a64aff2adf3d8e6de203c376cbff8 by nyalldawson

This mimics the existing @map_layers, @map_layer_ids, but unlike the
@map variants these return ALL project layers, not just those associated
with the current context's map settings.

Sponsored by SLYR

**Comment by DelazJ** [comment] 2020-03-20 21:48
Duplicate of #5064

**Closed by DelazJ** 2020-03-20 21:48 UTC
Labels: 3.14, Automatic new feature
