### ISSUE TITLE
Merge pull request #4256 from alexbruy/password-lineedit

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1761] opened 2017-03-14 17:26 UTC
Original commit: https://github.com/qgis/QGIS/commit/85776a1b82ac3078c956391df9d71dc2b8f27ea6 by web-flow

[FEATURE][needs-docs] new custom widget PasswordLineEdit

**Comment by DelazJ** [comment] 2017-03-14 17:40
duplicate of #1760

**Closed by DelazJ** 2017-03-14 17:40 UTC
Labels: Automatic new feature
