### ISSUE TITLE
Graduated Symbols in Layer Properties

### ISSUE THREAD

**Issue by gemsey1** [qgis/QGIS-Documentation#1697] opened 2017-02-19 10:45 UTC
I am using QGIS Desktop 2.18.3 (which I have just downloaded as I was getting this issue in a previous version as well, so hoped it was fixed in this version) and Windows 10. I am trying to use the graduated symbol function on some point data on one of my layers. When I click on the picklist to select the data I wish to graduate, the picklist is not populated with the attributes.
![grad](https://cloud.githubusercontent.com/assets/25878767/23101617/91273878-f68f-11e6-8d48-da913989121a.JPG)

When I go into categorize, the picklist is populated. 
![cat](https://cloud.githubusercontent.com/assets/25878767/23101616/9124a432-f68f-11e6-81ad-e569811b6f2c.JPG)

The data is from https://www.gislounge.com/a-web-mapping-tutorial-for-beginners/ and I can see no reason for it not to recognise the data as numbers to graduate. A copy of the attribute table is shown here. I am trying to graduate the column titles Number of.

![data](https://cloud.githubusercontent.com/assets/25878767/23101646/5e53585e-f690-11e6-9c4e-080aa7d2820a.JPG)

**Comment by Gustry** [comment] 2017-02-19 11:02
Hi,
This is not the best place to report an issue. This repository is about the documentation.

It's not a bug. Your field is a string, not a integer (looks your numbers are on the left side of the cell).
To use the graduated renderer, you need integers, not strings.

![int_string](https://cloud.githubusercontent.com/assets/1609292/23101745/230cc6a8-f69b-11e6-8238-7a4b5fb22a75.gif)

I used the field calculator to convert strings to integers.

**Comment by gemsey1** [comment] 2017-02-19 11:26
My apologies - thank you so much for your help.

**Comment by Gustry** [comment] 2017-02-19 11:39
Welcome.
One of the admin will close this issue.

**Comment by DelazJ** [comment] 2017-02-19 13:06
Thanks @Gustry

**Closed by DelazJ** 2017-02-19 13:06 UTC
