### ISSUE TITLE
Merge pull request #8781 from mhugent/get_atlas_print

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3310] opened 2019-01-07 09:42 UTC
Original commit: https://github.com/qgis/QGIS/commit/54a5fae0b7ba0b627e5e1aac691da02c04dc0585 by web-flow

[server][needs-docs] Get atlas print

**Comment by DelazJ** [comment] 2019-01-07 10:08
Duplicate of #3309

**Closed by DelazJ** 2019-01-07 10:08 UTC
Labels: Automatic new feature
