### ISSUE TITLE
Merge pull request #3931 from nirvn/processing_modeler_picture

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1604] opened 2017-01-02 08:50 UTC
Original commit: https://github.com/qgis/QGIS/commit/952e6fb17cbdc400d25f670529d2f75317176b6d by web-flow

[FEATURE] Export processing models as PDF/SVG

**Comment by DelazJ** [comment] 2017-01-02 09:44
duplicate of #1603

**Closed by DelazJ** 2017-01-02 09:44 UTC
Labels: Automatic new feature
