### ISSUE TITLE
Merge pull request #7004 from alexbruy/select-atribute

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2641] opened 2018-05-16 13:48 UTC
Original commit: https://github.com/qgis/QGIS/commit/e56ff6838dffd74cb1beb787641139c84be55a1e by web-flow

[processing][needs-docs] add selection methods to Select by attribute algorithm

**Comment by DelazJ** [comment] 2018-05-16 13:55
Duplicate of #2640

**Closed by DelazJ** 2018-05-16 13:55 UTC
Labels: Automatic new feature
