### ISSUE TITLE
[FEATURE] add a map canvas magnifier

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#1029] opened 2016-05-19 04:30 UTC
Original commit: https://github.com/qgis/QGIS/commit/9a62613b6b0e0c7e934c5b0bfe14ad6b921d9c5e by pblottiere

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-05-19 07:05
Duplicate of #1030

**Closed** 2016-05-19 07:05 UTC
Labels: Automatic new feature
