### ISSUE TITLE
[FEATURE][processing] New algorithm for calculating feature bounding boxes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1277] opened 2016-08-10 09:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/bd8db5d156071b308f9e091bc444857424879f06 by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-10 10:12
duplicate of #1280

**Closed by DelazJ** 2016-08-10 10:12 UTC
Labels: Automatic new feature
