### ISSUE TITLE
Merge pull request #7777 from PeterPetrik/mesh_vector_on_grid

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2968] opened 2018-09-06 13:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/1839daaa1891b4ecc94dcc7264440c3db656c20e by web-flow

[mesh] [feature] allow render vectors/arrows on the user-defined grid

**Comment by DelazJ** [comment] 2018-09-06 13:51
duplicate of #2967

**Closed by DelazJ** 2018-09-06 13:51 UTC
Labels: Automatic new feature
