### ISSUE TITLE
Merge pull request #33204 from olivierdalang/feature_random_seed_squashed

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4638] opened 2019-12-17 06:31 UTC
Original commit: https://github.com/qgis/QGIS/commit/98f8a897044dc758eacdc1d5594edad415ae2bd8 by web-flow

[FEATURE][expressions] allow to seed random functions

**Comment by DelazJ** [comment] 2019-12-17 06:54
Duplicate of #4637

**Closed by DelazJ** 2019-12-17 06:54 UTC
Labels: 3.12, Automatic new feature
