### ISSUE TITLE
[FEATURE][processing] Point on surface algorithm

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1279] opened 2016-08-10 09:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/142de7cb08601c3262974cc74689372d4652198c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-08-10 10:11
duplicate of #1282

**Closed by DelazJ** 2016-08-10 10:11 UTC
Labels: Automatic new feature
