### ISSUE TITLE
[FEATURE][processing] Add undo/redo support to model designer

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4996] opened 2020-03-10 22:40 UTC
Original commit: https://github.com/qgis/QGIS/commit/e7b5c2669617479650231ec5942dee1e92db9397 by nyalldawson

Makes QGIS more forgiving for users!

Sponsored by NRCan

**Comment by DelazJ** [comment] 2020-03-11 08:46
Duplicate of #4997

**Closed by DelazJ** 2020-03-11 08:46 UTC
Labels: 3.14, Automatic new feature
