### ISSUE TITLE
[3D] [Feature] Shadow rendering (#38448)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6097] opened 2020-09-10 13:02 UTC
Original commit: https://github.com/qgis/QGIS/commit/85e444e1d6c8c2463f03fe343801e35e11c87d74 by web-flow

* Initial post processing render pass implementation

* Got shadows with directional lights working good enough

* Make the shadows more configurable

* Trying to reduce peter panning

* Add licence

* banned banned_keywords_check

* trying to remove renderStateSet memory leak

* removing include <Qt3DExtras>

* Add documentation

* remove the use of setFilterMode when using QFilterLayer

* Fixing docs

* Fix shadow rendering checkbox

* Added y coordinates for view extent

* Added shadow bias parameter

* Added shadow map texture resolution parameter

* Addressing reviews

* Set the shadow rendering parameters automatically

* Add QLayer components individually if QT_VERSION < QT_5_10

* Hide depth texture preview quad

* Remove unused member

* Fix spell check

* Remove stepType property from shadowBiasSpinBox

* Disable shadow render pass if the shadow rendering is not activated

* Clarify maximum shadow rendering distance documentation

* Add value range for shadow bias

* Delete .bom file

* Clarify the usefullness of maximum shadow rendering distance

* remove unused stuff in shaders

* Make the inverted camera matrices passed as parameters

* Move post processing shaders parameters into the post processing entity constructor

* refactor how shadow rendering update into 1 function

* Fix spelling

* Fix Save As Image tool

* Improve UI according to suggessions

* add missing docs

* remove QAbstractSpinBox::DefaultStepType

**Comment by DelazJ** [comment] 2020-09-10 13:35
Duplicate of #6098

**Closed by DelazJ** 2020-09-10 13:35 UTC
Labels: 3.14, Automatic new feature
