### ISSUE TITLE
[FEATURE][layouts] Add import content from clipboard for fixed table items

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5192] opened 2020-03-31 10:21 UTC
Original commit: https://github.com/qgis/QGIS/commit/ab6fe9d79a7f0b1c26c3ffb7b3fc586223a94143 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-03-31 18:05
Duplicate of #5193

**Closed by DelazJ** 2020-03-31 18:05 UTC
Labels: 3.14, Automatic new feature
