### ISSUE TITLE
[qgsquick] [feature] Added identify and highlight feature

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2723] opened 2018-06-22 12:34 UTC
Original commit: https://github.com/qgis/QGIS/commit/264788ac21342d04ce2ca73cc5092dc0af1f0e18 by PeterPetrik

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2018-06-22 12:43
Duplicate of #2724

**Closed by DelazJ** 2018-06-22 12:43 UTC
Labels: Automatic new feature
