### ISSUE TITLE
[FEATURE] mesh simplification (#34532)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4936] opened 2020-02-25 07:05 UTC
Original commit: https://github.com/qgis/QGIS/commit/27a70eab7c54bc5e250d409c66645d3074b51f4a by web-flow

[FEATURE] fix #31575 mesh layer speed rendering improvements (LOD)

As mesh layer could have millions of triangles, rendering could be very slow, especially when all the triangles are displayed in the view whereas triangles are too small to be viewed.

For those situations QGIS has an option to simplify the mesh. Simplification leads to one or more simplified mesh that represents levels of detail (LOD). When rendering the mesh, the appropriate level of detail is chosen to have an adequate rendering depending on the view.

**Comment by DelazJ** [comment] 2020-02-27 07:39
Duplicate of #4937

**Closed by DelazJ** 2020-02-27 07:39 UTC
Labels: 3.12, Automatic new feature
