### ISSUE TITLE
[FEATURE] [OGR provider] Load/save style in database for GPKG and Spatialite

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1469] opened 2016-10-26 09:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/3b77e4b395c27d3c3b384bf9c519e7d1a075b9c2 by rouault

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-10-26 18:35
duplicate of #1471

**Closed by DelazJ** 2016-10-26 18:35 UTC
Labels: Automatic new feature
