### ISSUE TITLE
[needs-docs] Rework new project CRS handling

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3771] opened 2019-05-29 20:28 UTC
Original commit: https://github.com/qgis/QGIS/commit/dac7259b46521c41917e1f781b09e369d5c8b243 by nyalldawson

The previous approach was severely broken, because the default
CRS for new projects setting was ignored as soon as a layer
was added to the project.

Instead, refine the setting to add options
- "Use CRS from first layer added": same as previous behavior,
the project CRS is set to match the first layer added to a new
project
- "Use a default CRS": CRS for a new project is set to a preset
default CRS, and is left unchanged when adding layers to the
project

Also update qgis_global_settings.ini to reflect these changes.

Fixes #27516

**Comment by DelazJ** [comment] 2019-06-03 08:19
Duplicate of #3778

**Closed by DelazJ** 2019-06-03 08:19 UTC
Labels: Automatic new feature
