### ISSUE TITLE
Merge pull request #3411 from mhugent/feature_info_segmentized_geometry

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1352] opened 2016-08-25 15:39 UTC
Original commit: https://github.com/qgis/QGIS/commit/19dea08cf1850c95999e5d5e1291c22061ac451b by web-flow

[FEATURE]: possibility to segmentize feature info geometry in server

**Comment by DelazJ** [comment] 2016-08-25 15:47
duplicate of #1351

**Closed by DelazJ** 2016-08-25 15:47 UTC
Labels: Automatic new feature
