### ISSUE TITLE
PostgreSQL foreign tables: handle them like views (fixes #30990) [needs-docs]

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4057] opened 2019-07-31 23:05 UTC
Original commit: https://github.com/qgis/QGIS/commit/7084cb049938c63c974865a8cb84a2a4e2f73229 by nyalldawson

PostgreSQL foreign tables are not explicitely supported by the PosgreSQL provider.
This commit removes the error message, and handle foreign tables like views.

A foreign table cannot (in PostgreSQL <10) state what column
is the primary key, so we let the user tell QGIS.

**Comment by DelazJ** [comment] 2019-08-06 18:25
Duplicate of #4063

**Closed by DelazJ** 2019-08-06 18:25 UTC
Labels: Automatic new feature
