### ISSUE TITLE
[FEATURE] constraints on widgets

### ISSUE THREAD

**Issue by qgis-feature-tracker** [qgis/QGIS-Documentation#1100] opened 2016-06-01 15:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/020d20a968de9d38f5a622383c7404d8777e8088 by pblottiere

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2016-06-01 16:22
duplicate of #1101

**Closed by DelazJ** 2016-06-01 16:22 UTC
Labels: Automatic new feature
