### ISSUE TITLE
Merge pull request #3783 from nyalldawson/create_attribute_index

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1532] opened 2016-11-18 07:13 UTC
Original commit: https://github.com/qgis/QGIS/commit/72b4e72f05de753b6d21e3792119c8fe75238e20 by web-flow

[FEATURE][processing] Create attribute index algorithm

**Comment by DelazJ** [comment] 2016-11-18 07:55
duplicate of #1531

**Closed by DelazJ** 2016-11-18 07:55 UTC
Labels: Automatic new feature
