### ISSUE TITLE
[needs-docs] Memory layers can be safely duplicated now

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3942] opened 2019-07-02 00:10 UTC
Original commit: https://github.com/qgis/QGIS/commit/e32ca14896c68cbdd601a3f164c2239e7e26543e by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment] 2019-07-02 07:01
Duplicate of #3944.

**Closed by havatv** 2019-07-02 07:01 UTC
Labels: Automatic new feature
