### ISSUE TITLE
[FEATURE] Vector layer save as: offer file/layer overwriting, new layer creation, feature and field appending

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1453] opened 2016-10-17 09:22 UTC
Original commit: https://github.com/qgis/QGIS/commit/34894c6f5a9ed0fd93d25f72354f819b5b0cbd8c by rouault (see PR https://github.com/qgis/QGIS/pull/3597)

When saving a vector layer into an existing file, depending on the capabilities
of the output driver, the user can now decide whether:
- to overwrite the whole file
- to overwrite only the target layer (layer name is now configurable)
- to append features to the existing target layer
- to append features, add new fields if there are any.

All above is available for drivers like GPKG, SpatiaLite, FileGDB, ...
For drivers like Shapefile, MapInfo .tab, feature append is also available.

**Comment by DelazJ** [comment] 2016-10-25 08:51
duplicate of #1466

**Closed by DelazJ** 2016-10-25 08:51 UTC
Labels: Automatic new feature
