### ISSUE TITLE
[needs-docs] Upgrade project level setting for Label as Outlines/text setting to use newer API

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3236] opened 2018-12-11 02:28 UTC
Original commit: https://github.com/qgis/QGIS/commit/7ed4218b001d688f13cecd02631b874f3d2b819f by nyalldawson

And replace labeling engine dialog "Draw text as outlines" checkbox with a combobox
presenting the choice of always rendering as outlines OR text.

(This will allow us to easily add additional methods in future, e.g. potentially
a "Render as text wherever possible" setting, for defaulting to text objects
whenever it doesn't impact the rendering quality to do so)

**Comment by DelazJ** [comment] 2018-12-11 13:36
Duplicate of #3239

**Closed by DelazJ** 2018-12-11 13:36 UTC
Labels: Automatic new feature
