### ISSUE TITLE
Merge pull request #4336 from nyalldawson/background_raster

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1813] opened 2017-04-06 22:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/d26d1b7c4a3b949acdd1296e0b51ccc667d5c78e by web-flow

[FEATURE] Background saving of raster layers

**Comment by DelazJ** [comment] 2017-04-07 07:44
duplicate of #1812

**Closed by DelazJ** 2017-04-07 07:44 UTC
Labels: Automatic new feature
