### ISSUE TITLE
Merge pull request #4512 from nyalldawson/locator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1914] opened 2017-05-17 21:06 UTC
Original commit: https://github.com/qgis/QGIS/commit/b4de0acef540cc41da026a9aea39e288fd3fad06 by web-flow

[FEATURE] Implement a QtCreator style locator bar in the QGIS status bar

**Comment by DelazJ** [comment] 2017-05-17 21:27
duplicate of #1913

**Closed by DelazJ** 2017-05-17 21:27 UTC
Labels: Automatic new feature
