### ISSUE TITLE
Merge pull request #3393 from nyalldawson/processing_translate

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1299] opened 2016-08-15 11:41 UTC
Original commit: https://github.com/qgis/QGIS/commit/866617ccd398fbf6c6d4e98ec8a48393db068cde by web-flow

[FEATURE][processing] New algorithm for translating (moving) points

**Comment by DelazJ** [comment] 2016-08-15 17:01
duplicate of #1298

**Closed by DelazJ** 2016-08-15 17:01 UTC
Labels: Automatic new feature
