### ISSUE TITLE
Merge pull request #8289 from borysiasty/csv_string_quoting

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3099] opened 2018-10-24 16:37 UTC
Original commit: https://github.com/qgis/QGIS/commit/302529a10c8e5d033588985ed51b1cf7861625dd by web-flow

[needs-docs] Save layer as CSV: add STRING_QUOTING option to the predefined drop-down widgets

**Comment by havatv** [comment] 2018-10-25 06:40
The user guide does not go into detail on export options.  So I guess this should not be documented.

**Comment by DelazJ** [comment] 2018-10-25 09:52
Duplicate of #3098

**Closed by DelazJ** 2018-10-25 09:52 UTC
Labels: Automatic new feature, ToDocOrNotToDoc?
