### ISSUE TITLE
Merge pull request #3418 from nyalldawson/default_values2

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1364] opened 2016-08-30 03:25 UTC
Original commit: https://github.com/qgis/QGIS/commit/0658640fa0cdab6d53209f7a18cbb9fcf967d361 by web-flow

[FEATURE] Client side default values

**Comment by DelazJ** [comment] 2016-08-30 10:55
duplicate of #1365

**Closed by DelazJ** 2016-08-30 10:55 UTC
Labels: Automatic new feature
