### ISSUE TITLE
[FEATURE][locator] Add a goto locator

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5911] opened 2020-07-28 01:14 UTC
Original commit: https://github.com/qgis/QGIS/commit/44fd606595c7995aca80d6cf840e1ab62a699ef0 by nirvn

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-07-28 02:55
Duplicate of #5912

**Closed by DelazJ** 2020-07-28 02:55 UTC
Labels: 3.14, Automatic new feature
