### ISSUE TITLE
Merge pull request #3536 from nyalldawson/cluster_marker

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1435] opened 2016-09-30 04:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/ddcea34708bc6bccdb8f15cee82baf6a3bcec01e by web-flow

[FEATURE] Cluster marker renderer

**Comment by DelazJ** [comment] 2016-10-10 11:03
duplicate of #1434

**Closed by DelazJ** 2016-10-10 11:03 UTC
Labels: Automatic new feature
