### ISSUE TITLE
Merge pull request #33950 from DelazJ/renameMapTheme

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5341] opened 2020-04-23 14:55 UTC
Original commit: https://github.com/qgis/QGIS/commit/5d45b714218834e9585982b3a81a7fbc087fefa3 by web-flow

[feature] Allow renaming of the current map theme

**Comment by DelazJ** [comment] 2020-04-23 15:12
Duplicate of #5341

**Closed by DelazJ** 2020-04-23 15:12 UTC
Labels: 3.14, Automatic new feature
