### ISSUE TITLE
[MESH] scalar color settings depending on classification (#36313)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5464] opened 2020-05-11 05:19 UTC
Original commit: https://github.com/qgis/QGIS/commit/fca90a7bfbf49a96a73613706adda11b30803aee by web-flow

* [MESH] [FEATURE] Sets meh color ramp classification from metadata read by MDAL driver.
Some mesh layer formats can provide values that can be compressed by categorizing values in consecutive intervals, each represent by an integer or byte. MDAL has the capabilities to recognize this dataset type and store the bounds of each class an the units in the metadata.
QGIS uses this metadata to setup adapted color ramp shader.

* [MDAL] update to pre-release 0.5.92

**Comment by DelazJ** [comment] 2020-05-11 05:29
Duplicate of #5465

**Closed by DelazJ** 2020-05-11 05:29 UTC
Labels: 3.14, Automatic new feature
