### ISSUE TITLE
[processing][FEATURE] After running a model through the model designer,
show the obtained values for all child algorithm outputs within the designer
canvas

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5190] opened 2020-03-31 09:35 UTC
Original commit: https://github.com/qgis/QGIS/commit/5963b90f2ceb398ec1e24058e12dfe1ecef195b0 by nyalldawson

This gives users better tools for debugging models - they can see exactly
what values were output by the child algorithms and flowed into other
parts of their model

**Comment by DelazJ** [comment] 2020-03-31 18:06
Duplicate of #5191

**Closed by DelazJ** 2020-03-31 18:06 UTC
Labels: 3.14, Automatic new feature
