### ISSUE TITLE
Merge pull request #8863 from rldhont/server-wmts-config-matrices

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3372] opened 2019-01-17 18:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/67938e54263d9511f92530517492a6569b5f5bf0 by web-flow

WMTS tile matrices configuration [Server][Feature]

**Comment by havatv** [comment] 2019-01-18 07:55
Seems to be a duplicate of #3371.

**Closed by havatv** 2019-01-18 07:55 UTC
Labels: Automatic new feature
