### ISSUE TITLE
[feature] data defined control over layout map CRS

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#4933] opened 2020-02-22 20:51 UTC
Original commit: https://github.com/qgis/QGIS/commit/13337b20cd12b320d491827e9141ad13af363f18 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-02-27 07:40
Duplicate of #4934

**Closed by DelazJ** 2020-02-27 07:40 UTC
Labels: 3.12, Automatic new feature
