### ISSUE TITLE
link contexthelp buttons to doc site pages (resurrection of ContextHelp wiki page)

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS-Documentation#1926] opened 2017-05-31 06:13 UTC
ContextHelp pages

(copy of  http://hub.qgis.org/wiki/quantum-gis/ContextHelp, via redmine dump)

We checked all texts and contexts and buttons in this directory: https://github.com/qgis/QGIS/tree/master/resources/context_help

|*Filename in resources*      | *Context and Type of help 'button'*       | *TODO*  | *uri to use                                             * | *NOTES* |   *TAKER*  |
|-----------------------------|-------------------------------------------|---------|-----------------------------------------------------------|---------|------------|
|eVisDatabaseConnectionGui    |	Help only in one dialog: add a menu-item? | USE uri | docs/user_manual/plugins/plugins_evis.html              |||
|HeatMapGui	              |	Help (default button bar)	|	USE uri	|	docs/user_manual/plugins/plugins_heatmap.html#using-the-heatmap-plugin	|		|	|
|PythonConsole	              |	Little ?-icon in left bar	|	NEW WRITE !	|	?	|	NOT in docs yet (small part in cookbook) TO BE COPIED TO DOCS	|	|
|QgsAttributeTableDialog      |	Little ?-text Upper right corner	|	MERGE !	|	docs/user_manual/working_with_vector/editing_geometry_attributes.html#working-with-the-attribute-table	|		|	|
|QgsBookmarks	              |	Help (default button bar)	|	MERGE !	|	docs/user_manual/introduction/general_tools.html?highlight=bookmarks#spatial-bookmarks	|	NOTE: adding saving of bookmarks	|	|
|QgsComposer	              |	NOT FOUND	|	NO BUTTON? ADD:	|		|	cannot find a context help button, add it (in composer manager??)	|	|
|	                      |	add	|	QgsComposerManager	|	docs/user_manual/print_composer/print_composer.html#manage-the-composer	|		|	|
|	                      |	add	|	QgsComposer	|	docs/user_manual/print_composer/print_composer.html#print-composer	|		|	|
|QgsCustomProjectionDialog    |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_projections/working_with_projections.html#custom-coordinate-reference-system	|		|	|
|QgsDecorationCopyrightDialog |	Help (default button bar)	|	MERGE !	|	docs/user_manual/introduction/general_tools.html?highlight=copyright#copyright-label	|	merge only parts about the html options	|	|
|QgsDecorationNorthArrowDialog|	Help (default button bar)	|	USE uri	|	docs/user_manual/introduction/general_tools.html?#north-arrow	|		|	|
|QgsDecorationScaleBarDialog  |	Help (default button bar)	|	USE uri	|	docs/user_manual/introduction/general_tools.html?#scale-bar	|		|	|
|QgsDelimitedTextSourceSelect |	Help (default button bar)	|	MERGE !	|	docs/user_manual/working_with_vector/supported_data.html#delimited-text-files	|		|	|
|QgsFieldCalculator	      |	Help (default button bar)	|	NOT USE CONTEXT!	|	? docs/user_manual/working_with_vector/expression.html#functions-list	|	NOTE: these fields have separate helps in: ./resources/function_help/	|	|
|QgsGPSPluginGui	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_gps/plugins_gps.html	|		|	|
|QgsIdentifyResultsDialog     |	Help button NOT default!	|	USE uri	|	docs/user_manual/introduction/general_tools.html#identify	|		|	|
|QgsMeasureDialog	      |	Help button, NOT default	|	USE uri	|	docs/user_manual/introduction/general_tools.html#measure-length-areas-and-angles	|		|	|
|QgsNewOgrConnection	      |	Help (default button bar)	|	NEW WRITE !	|	no info in context, nor anything found in current documentation	|		|	|
|QgsNewSpatialiteLayerDialog  |	Help (default button bar)	|	MERGE !	|	docs/user_manual/working_with_vector/supported_data.html#creating-a-new-spatialite-layer	|		|	|
|QgsOpenVectorLayerDialog     |	Help (default button bar)	|	Merge ? Or just use uri	|	docs/user_manual/working_with_vector/supported_data.html#loading-a-shapefile	|		|	|
|QgsOptions	              |	Help (default button bar)	|	USE uri	|	docs/user_manual/introduction/qgis_configuration.html#options	|		|	|
|QgsOracleNewConnection	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_vector/supported_data.html#oracle-spatial-layers	|		|	|
|QgsPgNewConnection	      |	Help (default button bar)	|	MERGE !	|	docs/user_manual/working_with_vector/supported_data.html#postgis-layers	|		|	|
|QgsPgSourceSelect	      |	Help (default button bar)	|	MERGE !	|	docs/user_manual/working_with_vector/supported_data.html#loading-a-postgis-layer	|		|	|
|QgsPluginManager	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/plugins/plugins.html#the-plugins-dialog	|		|	|
|QgsProjectProperties	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/introduction/qgis_configuration.html?#project-properties	|		|	|
|QgsQueryBuilder	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_vector/query_builder.html#query-builder	|		|	|
|QgsSpatiaLiteSourceSelect    |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_vector/supported_data.html#spatialite-layers	|		|	|
|QgsStyleV2ManagerDialog      |	NOT FOUND	|	Obsolete?	|		|		|	|
|QgsVectorLayerProperties     |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_vector/vector_properties.html#the-vector-properties-dialog	|		|	|
|QgsVectorLayerSaveAsDialog   |	Help (default button bar)	|	MERGE !	|	docs/user_manual/working_with_vector/editing_geometry_attributes.html#save-selected-features-as-new-layer	|		|	|
|QgsWMSSourceSelect	      |	Help (default button bar)	|	USE uri	|	docs/user_manual/working_with_ogc/ogc_client_support.html#selecting-wms-wmts-servers	|		|	|
|RgSettingsDlg                |	Help (default button bar)	|	USE uri	|	docs/user_manual/plugins/plugins_road_graph.html#road-graph-plugin	|		|	|
|RgShortestPathWidget         |	Help (default button bar)	|	USE uri	|	docs/user_manual/plugins/plugins_road_graph.html#using-the-plugin	|		|	|
|         		      | 	      	|		|		|		|	|
|? data defined style properties|Missing?	|		|		|		|	|
|? selecting colors  	      |	Missing?	|		|		|		|	|
|? annotations	              |	Missing?	|		|	docs/user_manual/introduction/general_tools.html#annotation-tools	|		|	|

**Comment by DelazJ** [comment] 2017-07-29 15:55
Some updates at http://osgeo-org.1560.x6.nabble.com/Qgis-community-team-Let-s-bring-documentation-at-the-heart-of-QGIS-Desktop-td5329752.html

**Comment by DelazJ** [comment] 2018-08-28 11:46
I've tried to complete this list but gave up months ago given that there was likely no plan to implement the future-proof feature that dynamically keeps dialogs connected to help files without writers browsing the QGIS repo for each update. The live file is at https://framacalc.org/4hipbz1q7t and given that it's a temporary link and to not lose the effort, here's a [zip file](https://github.com/qgis/QGIS-Documentation/files/2327709/4hipbz1q7t.zip) for reference. In the case someone one day...

**Comment by havatv** [comment] 2020-05-24 22:48
Is this still an issue? The "Help" button for a tool seems to be "automatically" linked to the documentation.
If this is not solved, please re-open and provide information about what needs to be done.

**Comment by DelazJ** [comment] 2020-05-25 05:42
@havatv 
> >If this is not solved, please re-open and provide information about what needs to be done.

@DelazJ :roll_eyes: 
> plan to implement the future-proof feature that dynamically keeps dialogs connected to help files without writers browsing the QGIS repo for each update. 

There's no automatic connection with the help button, someone needs to add them. But that's not the report. The issue is that when the section is moved, someone (most of the time me) needs to go and update that in the source code. And it could be nice if the redirection is handled on the doc side and benefits to all the releases and not only from the one the updates has been done in (ie moving a section in 3.14 code would make 3.12 help button fail)
Hope that clarifies

**Comment by DelazJ** [comment] 2024-12-31 17:44
Well, page redirection has been implemented years ago. Not specifically a section redirection but it helps. Also I'm not sure the kind of connection I expected will/could ever been implemented, so I'm closing.

**Closed by DelazJ** 2024-12-31 17:44 UTC
Labels: Backend
