### ISSUE TITLE
Merge pull request #35901 from alexbruy/remove-functions

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5371] opened 2020-04-30 06:38 UTC
Original commit: https://github.com/qgis/QGIS/commit/60d568485df919ba783bf3b32144a9ed3b9c08b2 by web-flow

[feature] ability to remove custom functions (fix #27513)

**Comment by DelazJ** [comment] 2020-04-30 06:50
Duplicate of #5372

**Closed by DelazJ** 2020-04-30 06:50 UTC
Labels: 3.14, Automatic new feature
