### ISSUE TITLE
Arguments for functions in help show = to be used while examples show := 

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS-Documentation#6789] opened 2021-06-28 15:50 UTC
QGIS documentation arguments say for example offset=0.25 but to be able to use them you need to add : like offset:=0.25 which is not what the documentation says. Processing uses : as it uses dictionaries. Attached is one example but it is the same for all arguments I suppose

![image](https://user-images.githubusercontent.com/4627073/123665991-0920c000-d7f6-11eb-8702-77aa84508d93.png)

**Comment by DelazJ** [comment] 2021-06-28 16:33
@antoniolocandro I understand that it may be confusing to have a section called `Syntax` that does not really show the real/full(?) syntax (i.e. using `:=`) but then we would be talking about something to fix in the software itself. The QGIS-Documentation repository is meant for issues you'll encounter in https://docs.qgis.org. Please report instead in [qgis/QGIS](https://www.github.com/qgis/QGIS/issues) repository.

**Comment by antoniolocandro** [comment] 2021-06-28 16:49
I just think it should fix in the documentation, see this example I copied literally what is shown in the help and I get an error

![image](https://user-images.githubusercontent.com/4627073/123674020-5ef96600-d7fe-11eb-864b-c87fc8ca166f.png)

If I add the : now it works

![image](https://user-images.githubusercontent.com/4627073/123674072-6de01880-d7fe-11eb-8c88-0d6500e823da.png)

So is the error in the documentation or is the software? I don't have enough knowledge to decide so I would think is the documentation

**Comment by DelazJ** [comment] 2021-06-28 16:59
This is error in the software, with fix suggested at qgis/QGIS#43964

**Comment by DelazJ** [comment] 2021-06-28 17:04
> So is the error in the documentation or is the software? I don't have enough knowledge to decide so I would think is the documentation

Just to clarify: anything wrong you meet when you are using QGIS Desktop (be it function/processing results, help, description, GUI...) should be reported in qgis/QGIS repo. The issue is in the software.
Now if you are reading https://docs.qgis.org/3.16 (or any other version) and you find something incorrect, then you should report in this repository. This is what I'm referring to as "documentation".

**Comment by DelazJ** [comment] 2021-07-01 07:42
@antoniolocandro is there anything left with this report you think we need to fix in this repository or could it be closed?

**Comment by DelazJ** [comment] 2021-11-06 06:39
Closing. Please reopen if anything left. Thanks for understanding.

**Closed by DelazJ** 2021-11-06 06:39 UTC
