### ISSUE TITLE
Merge pull request #4237 from nyalldawson/filter_selected

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1747] opened 2017-03-08 23:23 UTC
Original commit: https://github.com/qgis/QGIS/commit/8f470e9a09bed0b68c084942481c3ca378933f95 by web-flow

[needs-docs] Attribute table "show selected features" shows no featureswhen none are selected

**Comment by DelazJ** [comment] 2017-03-09 10:57
Duplicate of #1746

**Closed by DelazJ** 2017-03-09 10:57 UTC
Labels: Automatic new feature
