### ISSUE TITLE
[needs-docs] Memory layers can be safely duplicated now

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3945] opened 2019-07-02 03:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/671bf9989c92a2ff92b3f0927ee997bee2e1895c by nyalldawson

Unfortunately this naughty coder did not write a description... :-(

**Comment by havatv** [comment] 2019-07-02 07:02
Duplicate of #3941.

**Closed by havatv** 2019-07-02 07:02 UTC
Labels: Automatic new feature
