### ISSUE TITLE
Merge pull request #3816 from nyalldawson/processing_datetime

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1553] opened 2016-12-01 10:37 UTC
Original commit: https://github.com/qgis/QGIS/commit/a17facf6cbc05ec2a0aaae7c01beed686bcce407 by web-flow

[processing][FEATURE] New unified basic stats algorithm

**Comment by DelazJ** [comment] 2016-12-01 10:45
duplicate of #1552

**Closed by DelazJ** 2016-12-01 10:45 UTC
Labels: Automatic new feature
