### ISSUE TITLE
[FEATURE][vectortiles] Allow users to load MapBox GL Json style
configuration files when importing style for vector tile layers

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#6075] opened 2020-09-07 06:00 UTC
Original commit: https://github.com/qgis/QGIS/commit/77492b1ea6bdbcc66f54144fc0b1fc39c5985245 by nyalldawson

From the standard layer properties -> Load Style dialog users
are now given the option of selecting a JSON MapBox GL style
file.

**Comment by DelazJ** [comment] 2020-09-07 14:04
Duplicate of #6076

**Closed by DelazJ** 2020-09-07 14:04 UTC
Labels: 3.14, Automatic new feature
