### ISSUE TITLE
[processing][needs-docs] By default, hide algorithms with known issues from toolbox

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3490] opened 2019-03-05 20:33 UTC
Original commit: https://github.com/qgis/QGIS/commit/63d648738d893890a48ab3fea175ded725f648e2 by nyalldawson

And add a Processing setting to allow these to be shown. When shown, they
are highlighted in red with a tooltip explaining that the algorithm
has known issues

**Comment by DelazJ** [comment] 2019-03-07 02:19
Duplicate of #3493

**Closed by DelazJ** 2019-03-07 02:19 UTC
Labels: Automatic new feature
