### ISSUE TITLE
Merge pull request #4355 from boundlessgeo/password-helper-authmanager3

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1821] opened 2017-04-12 11:04 UTC
Original commit: https://github.com/qgis/QGIS/commit/c9f0509841c565a3540c06f7665573461eede8c9 by web-flow

[feature][needs-docs] Master Password integration with OS password manager

**Comment by DelazJ** [comment] 2017-04-12 11:11
duplicate of #1820

**Closed by DelazJ** 2017-04-12 11:11 UTC
Labels: Automatic new feature
