### ISSUE TITLE
[FEATURE][symbology] Add data-defined property to font family/style for font markers (#35224)

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#5086] opened 2020-03-22 05:24 UTC
Original commit: https://github.com/qgis/QGIS/commit/f3e2ef1fe72e5ab18123101db00c0d3746ad6231 by web-flow

Unfortunately this naughty coder did not write a description... :-(

**Comment by DelazJ** [comment] 2020-03-23 16:28
Duplicate of #5087

**Closed by DelazJ** 2020-03-23 16:28 UTC
Labels: 3.14, Automatic new feature
