### ISSUE TITLE
Merge pull request #4625 from nyalldawson/comp_extent

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1931] opened 2017-06-01 04:01 UTC
Original commit: https://github.com/qgis/QGIS/commit/f359ffb5626725fd4a05b306b42696cf93644af8 by web-flow

[FEATURE] New decoration type for showing composer map extents

**Comment by DelazJ** [comment] 2017-06-01 07:51
duplicate of #1930

**Closed by DelazJ** 2017-06-01 07:51 UTC
Labels: Automatic new feature
