### ISSUE TITLE
[Feature] conditional visibility for tabs and groupboxes

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1387] opened 2016-09-09 12:56 UTC
Original commit: https://github.com/qgis/QGIS/commit/1882cabea9aeec06d726e9b17759165ef3ad75ab by m-kuhn

This adds a new configuration option to conditionally show or hide
tabs and groupboxes in drag and drop designer forms.

Configuration is done via a double click in the designer tree in the
fields configuration interface.

An expression can be entered to control the visibility. The expression
will be re-evaluated everytime values in the form change and the tab or
groupbox shown/hidden accordingly.

**Comment by DelazJ** [comment] 2016-09-14 08:34
duplicate of #1399

**Closed by DelazJ** 2016-09-14 08:34 UTC
Labels: Automatic new feature
