### ISSUE TITLE
[needs-docs][processing] Add option to check validity alg to ignore self-intersection
causing rings errors

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#3485] opened 2019-03-05 01:08 UTC
Original commit: https://github.com/qgis/QGIS/commit/850905e7a177cb3fb09ad7f014c36dfb4504214a by nyalldawson

By default the algorithm now uses the strict OGC definition of polygon validity, where
a polygon is marked as invalid if a self-intersecting ring causes an interior hole.
If the "Ignore ring self intersections" option is checked, then this rule will be
ignored and a more lenient validity check will be performed.

Refs #16418, refs #21336

(cherry picked from commit 49742c302afb97e6272ce8b6b3a806014cdbdb5b)

**Comment by DelazJ** [comment] 2019-03-07 02:21
Duplicate of #3492

**Closed by DelazJ** 2019-03-07 02:21 UTC
Labels: Automatic new feature
