### ISSUE TITLE
Merge pull request #4281 from nyalldawson/does_not_contain

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1773] opened 2017-03-21 21:38 UTC
Original commit: https://github.com/qgis/QGIS/commit/2e9f99693d568f438a0e0871487caaf02901d635 by web-flow

[FEATURE][processing] Add 'does not contain' to Extract By Attribute

**Comment by DelazJ** [comment] 2017-04-01 17:28
Duplicate of #1772

**Closed by DelazJ** 2017-04-01 17:28 UTC
Labels: Automatic new feature
