### ISSUE TITLE
Merge pull request #4652 from nyalldawson/extent

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#1929] opened 2017-06-01 00:02 UTC
Original commit: https://github.com/qgis/QGIS/commit/5077e1285ed0a582c54042a3f7ad7e615049bab9 by web-flow

[FEATURE] Add option to take extent from project map layer to QgsExtentGroupBox

**Comment by DelazJ** [comment] 2017-06-01 07:51
duplicate of #1928

**Closed by DelazJ** 2017-06-01 07:51 UTC
Labels: Automatic new feature
