### ISSUE TITLE
Merge pull request #6749 from slarosa/db_quey_history_1

### ISSUE THREAD

**Issue by QGIS-feature-tracker** [qgis/QGIS-Documentation#2608] opened 2018-05-07 09:01 UTC
Original commit: https://github.com/qgis/QGIS/commit/9d12b0ad7b77e73d751eb4dcd95c003e3c8bec64 by web-flow

[FEATURE][needs-docs] DB Manager: adds SQL query history

**Comment by DelazJ** [comment] 2018-05-07 10:10
Duplicate of #2607

**Closed by DelazJ** 2018-05-07 10:10 UTC
Labels: Automatic new feature
